### ISSUE TITLE
Quick question on ACL

### ISSUE THREAD

**Issue by Hax0rG1rl** [pwndoc/pwndoc#104]
Hi, 

Thank you for your work! :) 

I am playing with the current ACL system, and I would like to define a user simulating the role of a client who only needs to see: 

1. his project/download the report. 
2. all the other audits related to his profile and company. 

Initially, I have defined an ACL like this, but the new user gets pretty much full access to the "Data" section. 

```
{
    "report": {
        "inherits": ["user"],
        "allows": [
            "audits:read-all"
        ]
    },
    "client": {
        "inherits": ["user"],
        "allows": [
            "vulnerabilities:read",
            "vulnerabilities-updates:create",
            "vulnerabilities:update",
            "languages:read",
            "audit-types:read",
            "vulnerability-types:read",
            "vulnerabilities-categories:read"
        ]
    }
}
```

Then I have removed the inherit user rights bit, with the ACL pictured this way. However, this way, the user cannot see his project details, download the report or get access to the audits. 

```
{
    "report": {
        "inherits": ["user"],
        "allows": [
            "audits:read-all"
        ]
    },
    "client": {
        "allows": [
            "vulnerabilities:read",
            "vulnerabilities-updates:create",
            "vulnerabilities:update",
            "languages:read",
            "audit-types:read",
            "vulnerability-types:read",
            "vulnerabilities-categories:read"
        ]
    }
}
```

My aim is the new role, acting as a client, should not have the rights to display the "Data" section details, but only the details related to his allocated audits and profile. 

Any ideas on how the magic combination should look like looking to achieve this? 

Frankly, your ACL matrix is pretty straightforward, so I am scratching my head. 

Thank you!

**Comment by yeln4ts** [comment]
I didn't think about client access but it's a good idea and I'm going to think about it.
But for now you could try the following ACL:
```
"client": {
        "allows": [
            "audits:read",
            "images:read",
            "languages:read",
            "templates:read",
            "custom-fields:read"
        ]
    }
```
languages and templates are needed to display Audits list
audits:read, images:read and custom-fields:read will allow the user to only access audits where they are collaborators

With this normally the client won't be able to see any other data (the GUI allows access but nothing will be displayed)

**Comment by Hax0rG1rl** [comment]
Thank you!
