### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by noraj** [pwndoc/pwndoc#105]
It would be nice to have alternative Markdown support for findings fields rather than HTML. Using HTML or Markdown could be set up globally in the admin area.

Example of similar tool that has Markdown support: [writehat](https://github.com/blacklanternsecurity/writehat)

**Comment by yeln4ts** [comment]
The text has to be saved in HTML format so that it can be converted to OOXML when generating. Also not everything can be converted to OOXML right now (eg: tables). I don't see the necessity to handle both format when writing.
The only thing that I thought would be useful would be to have the option to convert some selected text from Markdown to HTML for people who take their notes in Markdown.

**Comment by noraj** [comment]
Markdown if meant to be transpilled as HTML and markdown renderers can accepts html tags and forwards them so sotring markdown would be backward compatible with vulns storing HTML. Generating the report  would be Markdown -> HTML -> OOXML then. So in fact we can keep markdown only while being backward compatible.

As most pentesters user markdown, that github issues/comment are using markdown, HackerOne issue are using markdown, etc. having markdown here would facilitate a lot.

**Comment by noraj** [comment]
I take this as a "No" then 😆

**Comment by noraj** [comment]
> This will enable markdown only for handled items (the ones in the toolbar).

**ON PASTE** It works only for bold, Strikethrough, italic and inline code. It doesn't work for lists, titles, code blocks, quotes even if they are on the toolbar.

**When writing** Everything in the toolbar works. Links are missing from the toolbar and so are not working.

I don't like much the render in place, is there an option to show the source (both for HTML or markdown)?

I also found some examples of Markdown editor with vue:

- https://vuejsexamples.com/a-cross-platform-markdown-text-editor/
- https://vuejsexamples.com/a-simple-example-of-a-markdown-editor-on-vue/
- https://vuejsexamples.com/a-simple-markdown-editor-with-vue-js/
- https://vuejsexamples.com/an-online-markdown-editor-built-with-vuejs/
- https://vuejsexamples.com/a-markdown-editor-component-for-vue-that-renders-in-place/
- https://vuejsexamples.com/a-vue-3-markdown-it-wrapper-plugin/
- https://vuejsexamples.com/example-markdown-editor-built-using-evwt/
- https://vuejsexamples.com/markdown-editor-built-on-vue/
- https://vuejsexamples.com/vue-markdown-editor-component-for-vue-js/
- https://vuejsexamples.com/the-vue-lib-for-markdown-it/
- https://vuejsexamples.com/markdown-editor-using-codemirror-and-previewer-using-showdown-for-vue-js/
- https://vuejsexamples.com/a-markdown-editor-based-on-vue-markdown-it/
- https://vuejsexamples.com/a-powerful-markdown-components-for-vue/
- https://vuejsexamples.com/a-vue-js-component-for-editing-and-previewing-markdown/

**Comment by yeln4ts** [comment]
Yes it seems there are some limitations when pasting when going through the tiptap issues. 

As I find that it's working correctly using HTML and I like the customizability of tiptap I wont change the editor.

Feel free to explore tiptap customization capabilities and if you find a way to make it work flawlessly I will gladly add it to the project.

**Comment by noraj** [comment]
Even for HTML could you enable the link shortcut on the editor.
