### ISSUE TITLE
[Request] more descriptive errors on templates

### ISSUE THREAD

**Issue by Darkcast** [pwndoc/pwndoc#110]
HI, 

I created a template and I upload it to the app I attach it to the audit when I try to download the audit report I get an undefined error it would be very helpful it there was a way it could tell me where it broke so I can go and fix it or at least why it broke. 

![2021-03-25_15-28](https://user-images.githubusercontent.com/1676655/112532424-2e2d0f00-8d7f-11eb-91ab-5daf5223191c.png)

thank you

**Comment by lm-sec** [comment]
I had the same issue at first and found that you can see the docx template errors on your backend logs when you try to export. Have you looked at those?

**Comment by AndyCyberSec** [comment]
> I had the same issue at first and found that you can see the docx template errors on your backend logs when you try to export. Have you looked at those?

where such logs can be seen?

**Comment by AndyCyberSec** [comment]
I guess this is the way: docker-compose logs -f pwndoc-backend

**Comment by yeln4ts** [comment]
Yes for now if the error is Undefined you should check the backend logs like mentioned by @AndyCyberSec
