### ISSUE TITLE
Custom sections and missing images in report

### ISSUE THREAD

**Issue by gelim** [pwndoc/pwndoc#112]
Hello,

it seems that whenever you include a custom section in your report, any images attached to it won't display.
I checked by two methods:

- add text+image in the Custom data (then reference that in the template) and add the custom section in the audit and generate report
- add text only in Custom data, add the custom section in the audit and customize it by adding a picture, and generate report

Can you acknowledge this is a missing feature or a bug?
Thanks a lot!

-- 
Mathieu

**Comment by lm-sec** [comment]
Hi, 

I just tested it on my side and I managed to get a custom section with pictures and text. Both my text and pictures are in the custom section field. 

Here is the associated template text that made it work: 

{-w:p summary.text}{@text | convertHTML}
{-w:p images}{%image}
Image 1 – {caption}{/images}{/summary.text}

![image](https://user-images.githubusercontent.com/21041333/112648204-a6e3a800-8e1f-11eb-9c28-ebfc27c7f546.png)

On the app, the custom section is built this way:

![image](https://user-images.githubusercontent.com/21041333/112648325-cc70b180-8e1f-11eb-8a9e-455a03fb0ec0.png)

**Comment by gelim** [comment]
Awesome, yeah got it Merci @lm-sec !

**Comment by gelim** [comment]
Closing as a solution has been provided
