### ISSUE TITLE
[Question]|[Feature] Custom order by and applied styles

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc/pwndoc#113]
I have a custom field within each issue named "impact", which as you may guess is used to assign the issue an impact rating (High, Medium and low. Possibly Info to be added at a later date).

Would it be simple enough to do the two following things:

1, add the option to order the issues by rating instead of CVSS score, if I can assign each impacting rating a numerical value to aid in this?

2, have styles applied to the impact rating in the same way as CVSS score?

I'm not expecting you to implement this as I think this is more of a personal request for my case than something wanted overall, I'm just wondering how easy would it be to implement?

Thanks for the input.

**Comment by relaxedricky** [comment]
Feels dirty repeating the `{#findings}` three times BUT it does what I need so thank you for the advice. I now have a nicely ordered report with the correct styling applied to each impact.

Should I keep this open as a feature request for when it can be done in the code or would you rather it closing off for now?

**Comment by yeln4ts** [comment]
This is something I want to focus on at some point so I'll mark it as an enhancement and keep it open
