### ISSUE TITLE
[Question] Count vulnerabilities 

### ISSUE THREAD

**Issue by AndyCyberSec** [pwndoc/pwndoc#118]
Hello, I was wondering if there's a way/workaround to count vulnerabilities based on severity and display the number in reports

**Comment by relaxedricky** [comment]
Is this what you are looking for?

https://pwndoc.github.io/pwndoc/#/docxtemplate?id=count

Count the number of vulnerabilities by CVSS severity.

Use in template document

`// Example counting 'Critical' vulnerabilities
{findings | count: 'Critical'}`

**Comment by AndyCyberSec** [comment]
yes thank you!
