### ISSUE TITLE
Checklists and Methodologies

### ISSUE THREAD

**Issue by Tim-Conrad** [pwndoc/pwndoc#121]
It would be nice to allow users to create checklists for specific methodologies

**Comment by relaxedricky** [comment]
I believe you should be able to use a [custom section](https://pwndoc.github.io/pwndoc/#/audits?id=custom-sections) to create such a checklist to work through / add to an audit

**Comment by yeln4ts** [comment]
Yes you can create a Custom Section for that. Custom sections can now have multiple custom fields (and soon to be released a checkboxes field)
