### ISSUE TITLE
Export vulnerabilities from an audit

### ISSUE THREAD

**Issue by Tim-Conrad** [pwndoc/pwndoc#122]
It would be nice to have a way to export a issue set from an audit.

**Comment by lm-sec** [comment]
Is there a format you are thinking about? json? csv? I was wondering if this PR here, once completed, would satisfy this issue: 

https://github.com/pwndoc/pwndoc/pull/111 

The export as json lets you extract the report in the json format, which of course includes the different vulnerabilities.

**Comment by yeln4ts** [comment]
Yes this PR is in my Todo and would satisfy this request.
