### ISSUE TITLE
Update docxtemplater

### ISSUE THREAD

**Issue by noraj** [pwndoc/pwndoc#13]
Update docxtemplater to 3.19

https://github.com/pwndoc/pwndoc/blob/3ef0942d5124d90f307fba623cad0ce4a765b30f/backend/package.json#L28-L29

## Why?

- 3.2.0+ `Add paragraphLoop option, that permits to have better rendering for spaces`
- 3.2.3+ `Add support for Office365 generated documents`
- 3.4.0+ `Add change delimiter syntax from inside template`, `Add getTags to InspectModule.`
- 3.4.2+ `Add getAllTags to inspectModule`
- 3.8.3+ `Add templating of more meta data of the document, including : Author, Title, Topic, marks, Categories, Comments, Company`
- Many more
- 3.17.7+ `Add support for dotx and dotm file formats`
- Better performance
- Lot of small fixes & enhancements

Beware of breaking changes in:

- [3.4.1](https://github.com/open-xml-templating/docxtemplater/blob/master/CHANGELOG.md#341)

**Comment by yeln4ts** [comment]
docxtemplater-image-module is not maintained anymore and is now a paying module. 
So yes I plan to check if updating docxtemplater will break things with the image module or not very soon

**Comment by noraj** [comment]
It seems that the "docxtemplater-image-module" module is not on npmjs anymore (https://www.npmjs.com/search?q=docxtemplater-image-module).

But it seems that ["@docs-dispatcher.io/docxtemplater-image-module"](https://www.npmjs.com/package/@docs-dispatcher.io/docxtemplater-image-module) is maintained (last release 5 months ago) and compatible:

> This repository holds an maintained version of docxtemplater image module.
> This package is open source. There is also a paid version maintained by docxtemplater author.
> Note this version is compatible with docxtemplater 3.x.
