### ISSUE TITLE
idea for vulnerabilities

### ISSUE THREAD

**Issue by Darkcast** [pwndoc/pwndoc#130]
it would be cool if one could use this api to just pull the information for cve, summary, cvss score etc instead of having to add them manually that takes a ton of manual work from the users. 

https://cve.circl.lu/api/

https://cve.circl.lu/

**Comment by yeln4ts** [comment]
CVE are product,vendor,version specific, which is not the goal in this application as there would be too many vulnerabilities to handle. They could be used for specific cases though where fetching them online could be a good idea.
But most of the time you will use higher level vulnerabilities like CWE for examples.
As a starting "pack" you could check issue #45
