### ISSUE TITLE
Custom order of issues

### ISSUE THREAD

**Issue by kosztyua** [pwndoc/pwndoc#132]
Hi,
How would you approach implementing a custom order of the issues, as in drag&drop in the sidebar? I greatly enjoy using pwndoc but sometimes I need to reorder the issues after they have been generated, and allowing to change that on the interface would greatly help. I understand that the order is based on the order the issues are created and then normally changed by criticality, but this is very limiting, sometimes I want to emphasize / bring forward an issue and move others to the back.

**Comment by Darkcast** [comment]
I know the feeling man, what I do is fudge the cvss number a bit to get them where I need them and then edit them back in the word doc.

**Comment by yeln4ts** [comment]
I'm thinking about a way to handle that. 
The goal would be to add the possibility to customize the sorting parameters so that we could use any field or custom field.
Also adding an option to enable/disable automatic sorting so that if it's disabled you could manually drag&drop findings order.

**Comment by yeln4ts** [comment]
This is now implemented in the v0.4.0. You have a great number of options to sort your findings either automatically or with drag&drop
