### ISSUE TITLE
Affected host HTML table

### ISSUE THREAD

**Issue by thecasual** [pwndoc/pwndoc#135]
I am attempting to create a table in "affected" using:

{@affected | convertHTML}

When I populate "Affected Assets" in the "Details" tab with HTML data, it does not get converted into a table in word. Can you take a look at this?

https://docxtemplater.com/modules/html/

**Comment by yeln4ts** [comment]
You can't for now tables are not supported (it's in my roadmap). Moreover you shouldn't be able to have a table in the editor.
What you see in the editor is what you get in the report.

The module you are referring to is a paying module so I can't use it in this project.

**Comment by thecasual** [comment]
If you point me in the right direction, I wouldn't mind taking a stab at tables. It is something that I would like to see in the product. Let me know what you think.

**Comment by yeln4ts** [comment]
This would involve 2 components I think:
- Frontend: the editor (tiptap)
- Backend: the HTML to OOXML conversion (using docxjs: https://docx.js.org/#/usage/tables)

**Comment by BetaMaxHeadroom** [comment]
Would using markdown allow for tables to be added with the pipe and underscore characters? My limited understanding of this application is that HTML is converted to OOXML. I am not knowledgeable enough to know what the best method could be to get markdown to work with OOXML.

- If it makes more sense to convert markdown to HTML and then HTML to OOXML, then something like this could be an option: https://github.com/showdownjs/showdown
- If it makes more sense to convert markdown directly to OOXML, then this could be an option: https://github.com/o-slash/rodvila

I don't really know how to best go about this. I'm not the strongest coder. But, I would be happy to help where I can.

**Comment by yeln4ts** [comment]
Closing as there already is an issue about table feature #75
