### ISSUE TITLE
[Question] Identifier number per severity

### ISSUE THREAD

**Issue by survivelater** [pwndoc/pwndoc#136]
Hi,

as currently, my findings summary is in table sorted by severity and i notice that the identifier number is all over the place.
and doesn't look good to be sorted by identifier which will make the severity all over the place.
so I am wondering if anyone can help me with the identifier to be identify by severity.

for example:
C-001
H-001
H-002
M-001
M-002
L-001
N-001

rather than the current one where the numbering is for the whole of finding array but what I want is numbering by severity.

thanks

**Comment by yeln4ts** [comment]
This is not possible automatically.

To achieve that you would need to add a custom field for your finding ID and manually name it for each finding. Then use it instead of the current identifier in the report.
