### ISSUE TITLE
Custom Category not working as expected

### ISSUE THREAD

**Issue by z4t01** [pwndoc/pwndoc#137]
Hi,

I am trying to update the fields (adding/removing) of a custom category without success.
This is the test to reproduce the problem:

1) create a custom vulnerability "test vuln" category "CUSTOMABCD"
2) create a new vulnerability and set its category to "CUSTOMABCD"
3) open the custom data config page and add a custom field to "CUSTOMABCD" category
4) save

Result: "test vuln" vulnerability will not present the added custom field.
The only way to update the vulnerability with the new field is to change (reset, "select again") its category to "CUSTOMABCD" but this will reset all the previous associated data.

Any feedback?

Thanks

Tested on version **0.3.0 (2021-06-07)**

**Comment by yeln4ts** [comment]
I can't reproduce your issue.
When adding custom fields to a vulnerability category it will be automatically present when editing the vulnerability.
Can you paste screenshots of

- Data > Custom Data > Custom Fields > Vulnerability View > CUSTOMABCD Category
- Vulnerabilities > test vuln modal (custom fields part)
