### ISSUE TITLE
10 Tests failing on branch master

### ISSUE THREAD

**Issue by lm-sec** [pwndoc/pwndoc#139]
Hi, 

10 tests are currently failing on my and my colleague's ends. I think that whoever edited how the custom sections work forgot to adapt the tests to match the new intended behaviour. 

Here is the log of our output from running the full tests
[test.log](https://github.com/pwndoc/pwndoc/files/6663568/test.log)

**Comment by yeln4ts** [comment]
Yes I didn't updated tests for a long time, it's on my todo list but I always delay it 😅

**Comment by MaxNad** [comment]
Tests should be working once PR #448 is merged.
