### ISSUE TITLE
Custom field - Bullets are shown as ordered list in report

### ISSUE THREAD

**Issue by lisandre33** [pwndoc/pwndoc#140]
Hi,

I created a custom field labeled "accounts" of type "Editor" for Findings. When using it in an audit, I wrote a list of items using a bullet list. When generated in the report, it generates an ordered list (with numbers) instead of bullets. 
![PwnDoc Bug - within PwnDoc](https://user-images.githubusercontent.com/33424856/122253337-122a9c80-ce9a-11eb-9a8c-67aed1e43035.png)
![PwnDoc Bug - within the Word report template](https://user-images.githubusercontent.com/33424856/122253350-15258d00-ce9a-11eb-9175-415872a2242a.png)
![PwnDoc Bug - within the Word report](https://user-images.githubusercontent.com/33424856/122253362-1787e700-ce9a-11eb-91fb-4fd58f2a00cc.png)

**Comment by yeln4ts** [comment]
It must be because of wrong references in `numbering.xml`.
You can have more details in the documentation: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=styles

**Comment by nobox910** [comment]
@lisandre33,
you can workaround by swap number & bullet as the image below:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/58721688/122325136-3ba7fe80-cf54-11eb-8be0-8bce3369422e.png">

**Comment by yeln4ts** [comment]
This is always better to make your docx match the application than modifying code. There are several cases where this workaround won't work

**Comment by pierinogiorgio** [comment]
How come this major problem isn't fixed yet? :(
