### ISSUE TITLE
Add collaborator email & contact number 

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc/pwndoc#145]
While the collaborator's first name and last name can be used within reports, I think it would be useful if email addresses and contact numbers could be added to a collaborator (in the same way it can be added to a client) so these can be added within the report in an automated fashion.

**Comment by relaxedricky** [comment]
I'm aware this could be added as a custom bit of data, just thought it would make more sense linking it to the user account directly

**Comment by lm-sec** [comment]
Would this PR resolve your issue? 

https://github.com/pwndoc/pwndoc/pull/154

**Comment by relaxedricky** [comment]
Yes, it would. Amazing work, thank you.
