### ISSUE TITLE
Multiple vulnerability during installation?

### ISSUE THREAD

**Issue by pentestpurpose** [pwndoc/pwndoc#153]
Hi All,

Just checking if this is a false positive during installation?

```
found 9648 vulnerabilities (4710 low, 207 moderate, 4730 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Is it false positive and can be ignored? I do have installation log for reference shall it be needed.
Thanks in advance.

**Comment by lm-sec** [comment]
It mostly means that some packages are out of date and that some vulnerabilities were found on these packages. If pwndoc is vulnerable highly depends on the functions used in the packages and the context around it. An "update packages" pull request would probably be a good idea though. If you find the time, do not hesitate.
