### ISSUE TITLE
Problems with custom select fields

### ISSUE THREAD

**Issue by Fopje** [pwndoc/pwndoc#157]
When using the select fields with custom sections it gives 2 problems:

1. After adding a section with several options to for example the vulnerability view, it's not possible to update the options below. When deleting/adding options it appears to change, but after saving it's back at the previous contents.

![image](https://user-images.githubusercontent.com/4934752/126620374-fefbba40-b54a-4a49-8ac3-d02115c2ae5f.png)
![image](https://user-images.githubusercontent.com/4934752/126620419-ffdcad8b-91b9-4fdb-ba95-fb31f320c1ab.png)
![image](https://user-images.githubusercontent.com/4934752/126620444-070dc58f-98bb-4e10-bf52-bae01632dfe7.png)
![image](https://user-images.githubusercontent.com/4934752/126620473-a208bd8e-f4c5-4ef0-b134-d2fff2c05372.png)

2. When selecting a default value for audits in select component, it doesn't parse the content while generating the report.

![image](https://user-images.githubusercontent.com/4934752/126620738-7aa424d4-226e-4120-96f6-5e168948c90d.png)
![image](https://user-images.githubusercontent.com/4934752/126620841-c86c4b46-f320-403b-a622-7ab9d6c61e20.png)
![image](https://user-images.githubusercontent.com/4934752/126620949-6c5a076b-551e-4557-9f4f-e930db014aa9.png)

Only when selecting a value in an audit by hand it will be parsed when generating.

**Comment by yeln4ts** [comment]
1. I can't reproduce your issue. Maybe check the language if you have multiple to be sure to add options to the correct one. Also what version of pwndoc are you using ?
2. This I can reproduce thank you I will add it to my issues roadmap

**Comment by Fopje** [comment]
> 1. I can't reproduce your issue. Maybe check the language if you have multiple to be sure to add options to the correct one. Also what version of pwndoc are you using ?

I'm using the latest version (3.0.0). I only have one language at the moment.

![image](https://user-images.githubusercontent.com/4934752/126661005-5d5a857f-1e27-459d-b38c-ff3c2a836074.png)
![image](https://user-images.githubusercontent.com/4934752/126660742-dba7108b-8017-4bea-8360-6dd0392095f6.png)
![image](https://user-images.githubusercontent.com/4934752/126660377-97f6be81-8d57-473f-bc63-d200a22a9452.png)
![image](https://user-images.githubusercontent.com/4934752/126660433-1b492449-4243-4323-ba68-c1c6b3b27701.png)
![image](https://user-images.githubusercontent.com/4934752/126660506-1c03fb97-075c-4e56-b6ab-8a691fb2e2fd.png)
![image](https://user-images.githubusercontent.com/4934752/126660554-b0816529-5419-4fb1-996b-4708dfd2a6a2.png)
![image](https://user-images.githubusercontent.com/4934752/126660591-35522ebb-513a-49d8-847d-4a6ec0b2b0ab.png)

**Comment by yeln4ts** [comment]
I tried using a fresh instance of pwndoc, using the same parameters as you and could not reproduce your issue.

Created Custom Field select with 2 options
![image](https://user-images.githubusercontent.com/4255028/126678600-17547e73-16b4-4471-9344-e96769d24614.png)

Add a third option and click Save button
![image](https://user-images.githubusercontent.com/4255028/126678685-435cb2da-85bc-4519-b98a-ef4b07234550.png)

Third option is correctly here
![image](https://user-images.githubusercontent.com/4255028/126678827-81cb6e13-2b4c-48da-b507-c6d2fb2e3dbe.png)

Can you open the browser development console and check if there are any errors ? Also check for the backend logs ?

**Comment by Fopje** [comment]
> Can you open the browser development console and check if there are any errors ? Also check for the backend logs ?

I've tried in the latest version of Chrome and Firefox, the funcionality doesn't work, but I'm not getting any errors either. Next week I'm moving to production with a fresh installation, I'll see how it goes there and let you know.

**Comment by get-fooby** [comment]
You need to make a new Audit for the changes to be reflected in any of my tests. You cannot start an Audit, then edit the backend fields then return to an already created Audit to see the change.
Add your values, create a new audit and test it there.

**Comment by Fopje** [comment]
> You need to make a new Audit for the changes to be reflected in any of my tests. You cannot start an Audit, then edit the backend fields then return to an already created Audit to see the change.
> Add your values, create a new audit and test it there.

These are screenshots of the settings, where you make the field. This isn't inside a audit yet.

**Comment by Fopje** [comment]
> 2. This I can reproduce thank you I will add it to my issues roadmap

In the fresh installation this isn't a problem anymore.
