### ISSUE TITLE
Can't find the FINDINGS sub-section under Audits

### ISSUE THREAD

**Issue by NamrataSP** [pwndoc/pwndoc#161]
Hi, 
I just find general info and network scan section under my audits tab. Can you tell me clearly how to add a finding to a particular audit ? or atleast how can I get the findings tab under every audit.
![image](https://user-images.githubusercontent.com/87634546/126949031-5f7cac2f-4c48-42dd-9ba4-12ffbbd6a3b2.png)

**Comment by Fopje** [comment]
> Hi,
> I just find general info and network scan section under my audits tab. Can you tell me clearly how to add a finding to a particular audit ? or atleast how can I get the findings tab under every audit.
> ![image](https://user-images.githubusercontent.com/87634546/126949031-5f7cac2f-4c48-42dd-9ba4-12ffbbd6a3b2.png)

Did you check this box by accident?

![image](https://user-images.githubusercontent.com/4934752/126976247-601162a7-015a-412c-94de-beb055e419e6.png)

**Comment by NamrataSP** [comment]
Hey, Yes. Thanks a lot.
