### ISSUE TITLE
[ENHANCEMENT] Add some new customized fields to the report

### ISSUE THREAD

**Issue by NamrataSP** [pwndoc/pwndoc#162]
My team loved this tool and would like to go ahead and do some customization to generate our org specific reports. 

We have some data fields that have to be added to the report. I have a word/docx template that is specific to our requirements. 
How and where do I make the changes to the template to generate reports with required data. Is it okay if I only change the default template file in template folder? Or do I have to change some data in other files too?

Would be real helpful if you had some pointers soon.

I am not much familiar with nodejs, so it'd be helpful if you suggested some means to implement this.

**Comment by relaxedricky** [comment]
Hi,

Custom sections can be added, if you goto data > custom data, you will have a number of options.

One example would be to add a custom section named "executive":

![image](https://user-images.githubusercontent.com/6837440/127306359-d33eb364-c6d0-4fc1-aedc-f766ace19a88.png)

Then under custom fields select audit section, select "executive" as the section, and enter a label, in this example I used "summary":

![image](https://user-images.githubusercontent.com/6837440/127306614-0c1916ad-41bd-4b99-97d4-bbfa8b250be5.png)

Then click add. Now when you create a new audit, you should have an "executive" option to the left with a "summary" option being shown when you click the option on the left:

![image](https://user-images.githubusercontent.com/6837440/127307039-aacfa5c3-511f-4e8f-9597-a5836dc94d2c.png)

Now you would just need to add the following within your report template:

```
{#executive.summary}
{@text | convertHTML}
{/executive.summary}
```

This should give you a good base on how you add custom sections to your report.

**Comment by NamrataSP** [comment]
Thanks for the help on custom sections.

Also I imported some Nessus and Nmap scans into the utility. Is there any way in which I can add the data into the generated report?
In addition, can I integrate some OS utilities like MobSF with pwndoc? or is that limited only to infra tools
