### ISSUE TITLE
Error: Raw tag not in paragraph When I try to generate report

### ISSUE THREAD

**Issue by br33z3** [pwndoc/pwndoc#163]
When I try to generate report I get internal error. Also Docker log says;

Error: Raw tag not in paragraph
pwndoc-backend     |     at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend     |     at throwExpandNotFound (/app/node_modules/docxtemplater/js/errors.js:190:13)
pwndoc-backend     |     at expandOne (/app/node_modules/docxtemplater/js/traits.js:189:7)
pwndoc-backend     |     at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:241:22)
pwndoc-backend     |     at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend     |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:174:30
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:154:32)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend     |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20) {
pwndoc-backend     |   properties: {
pwndoc-backend     |     id: 'raw_tag_outerxml_invalid',
pwndoc-backend     |     explanation: 'The tag "image" is not inside a paragraph',
pwndoc-backend     |     rootError: Error: No tag "w:t" was found at the left
pwndoc-backend     |         at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend     |         at throwXmlTagNotFound (/app/node_modules/docxtemplater/js/errors.js:138:13)
pwndoc-backend     |         at getLeft (/app/node_modules/docxtemplater/js/doc-utils.js:404:3)
pwndoc-backend     |         at expandOne (/app/node_modules/docxtemplater/js/traits.js:185:12)
pwndoc-backend     |         at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:241:22)
pwndoc-backend     |         at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend     |         at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |         at Array.reduce (<anonymous>)
pwndoc-backend     |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend     |         at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20)
pwndoc-backend     |         at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:174:30
pwndoc-backend     |         at Array.reduce (<anonymous>)
pwndoc-backend     |         at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:154:32)
pwndoc-backend     |         at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |         at Array.reduce (<anonymous>)
pwndoc-backend     |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22) {
pwndoc-backend     |       properties: [Object]
pwndoc-backend     |     },
pwndoc-backend     |     xtag: 'image',
pwndoc-backend     |     offset: 3801,
pwndoc-backend     |     postparsed: [
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object]
pwndoc-backend     |     ],
pwndoc-backend     |     expandTo: 'w:t',
pwndoc-backend     |     index: 0,
pwndoc-backend     |     file: 'word/document.xml'
pwndoc-backend     |   }
pwndoc-backend     | }
pwndoc-backend     | TypeError: Cannot read property 'substring' of undefined
pwndoc-backend     |     at /app/src/lib/report-generator.js:89:118
pwndoc-backend     |     at Array.map (<anonymous>)
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:88:59)
pwndoc-backend     |     at runMicrotasks (<anonymous>)
pwndoc-backend     |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
pwndoc-backend     | Error: Raw tag not in paragraph
pwndoc-backend     |     at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend     |     at throwExpandNotFound (/app/node_modules/docxtemplater/js/errors.js:190:13)
pwndoc-backend     |     at expandOne (/app/node_modules/docxtemplater/js/traits.js:189:7)
pwndoc-backend     |     at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:241:22)
pwndoc-backend     |     at ImageModule.postparse (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:123:27)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend     |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:174:30
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:154:32)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend     |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20) {
pwndoc-backend     |   properties: {

**Comment by br33z3** [comment]
a

**Comment by get-fooby** [comment]
The same happens to me if I make one edit to the original template using Word 2016. If I import the existing template, with no changes - then the report exports as expected with no issues.

Let me know if i can help / test

**Comment by get-fooby** [comment]
So further inspection - editing the template document and re-uploading doesn't work. 

Making your own template and porting in the tags as appropriate does work. Don't try to edit the original template, but use it to inspire your own.

This is working for me so far.
