### ISSUE TITLE
Custom sections content disappeared after update

### ISSUE THREAD

**Issue by gelim** [pwndoc/pwndoc#165]
Hello,

After having updated to pwndoc to 02d144db4b58aec98a9870f5b7743589754298ce I am not able to see text input form for custom sections. In Data / Custom data / Custom Sections. In "List of Sections" there is only Name, Field, Icon as text input fields. The section name will appear properly in the report, but content is void.

What could be the explanation and a potential fix?
Thanks!

-- Mathieu

**Comment by relaxedricky** [comment]
I have a feeling you've not updated in a while, custom data has changed how it works: https://github.com/pwndoc/pwndoc/commit/3e07d39ea449e039bc5c010608a955dbae7bba96

A quick example of how custom data can be used is shown here: #162

**Comment by gelim** [comment]
Excellent, thanks @relaxedricky, I was missing those changes from the UI point of view, and #162 perfectly explains the modifications.
:+1:
