### ISSUE TITLE
Importing data and generating report

### ISSUE THREAD

**Issue by NamrataSP** [pwndoc/pwndoc#168]
Hi,
Can I integrate some OS utilities like MobSF with pwndoc? or is that limited only to infra tools

**Comment by relaxedricky** [comment]
pwndoc doesn't really integrate with any tool (other than import network scans).

My understanding is that the tool is focused on being a reporting tool, you build up the issue database to your needs. It isn't intended to be a tool where you import a Nessus and Burp file, then get a report spat out.

**Comment by NamrataSP** [comment]
Thanks a lot for the update,
I've imported some Nmap reports with host data into the utility, is it possible to add those data to the report?

**Comment by relaxedricky** [comment]
I got an email this morning saying you replied to this issue but for some reason, Github isn't showing it:

> Thanks a lot for the update,
> I've imported some Nmap reports with host data into the utility, is it possible to add those data to the report?

After importing the scan as per [network-scan](https://pwndoc.github.io/pwndoc/#/audits?id=network-scan)

You can use the results within your report, example code can be found within the [scope](https://pwndoc.github.io/pwndoc/#/docxtemplate?id=scope) section of the docs.
