### ISSUE TITLE
Sort vulnerabilities by categories

### ISSUE THREAD

**Issue by lilemark** [pwndoc/pwndoc#170]
Hello, 
I am new here and trying to explore the pwndoc. It is quite fun and really easy to work with but i am having an issue here with sorting the vulnerabilities(findings) by the categories. 
I would kindly ask you, how can i sort the vulnerabilities based on categories on the docx file?

Thank you for your time!

**Comment by relaxedricky** [comment]
Hi,

If you want to split the findings up based on categories I would recommend using something like the following:

`{#findings} {#category == 'web'} {title} {/category == 'web'} {/findings}`

web being an example categorie.

**Comment by lilemark** [comment]
Hi,

thank you for helping me out. It does work but when i include withing the {#findings} together with:  ```
{#cvssSeverity == 'Critical'}{@cvssColor} cvssSeverity} 
```
It does through me an error. Is there any syntax for accepting also the category and cvssSeverity in one field?

**Comment by relaxedricky** [comment]
Hi,

Can you give me the full syntax for what you tried as well as the error that is logged, you can use the following command to view the error:

`docker-compose logs -f pwndoc-backend`

**Comment by lilemark** [comment]
The syntax i tried on a table which is: 
```
{#findings} {#category == 'web'} {#cvssSeverity == 'Critical'}{@cvssColor}{cvssSeverity}
{@affected | convertHTML}{/category == 'web'}{/cssSeverity == 'Critical'}{/findings}
```
When trying to download a report, throws me 'undefined' error

**Comment by lilemark** [comment]
Hi,

yes, here is the error from the logged:
_explanation: 'The raw tag "affected | convertHTML" should be the only text in this paragraph. This means that this tag should not be surrounded by any text or spaces.',_  

I cannot fix it, do you have any idea?

**Comment by relaxedricky** [comment]
Ok the error message itself tells you what the issue is:

> explanation: 'The raw tag "affected | convertHTML" should be the only text in this paragraph. This means that this tag should not be surrounded by any text or spaces.',

So currently you have the following:

```
{#findings} {#category == 'web'} {#cvssSeverity == 'Critical'}{@cvssColor}{cvssSeverity}
{@affected | convertHTML}{/category == 'web'}{/cssSeverity == 'Critical'}{/findings}
```

As you can see, the `{@affected | convertHTML}` tag isn't the only text in this paragraph, it is surrounded by other text and spaces.

Based on your code and the error I think it is asking for the following:

```
{#findings} {#category == 'web'} {#cvssSeverity == 'Critical'}{@cvssColor}{cvssSeverity}
{@affected | convertHTML}
{/category == 'web'}{/cssSeverity == 'Critical'}{/findings}
```

**Comment by lilemark** [comment]
Thank you for your time :) , I appreciate this.
I am also getting another error when fixed the last one. It is: 
 _explanation: `The tag "category == 'web'" is closed by the tag "cvssSeverity == 'Critical'"`,_                      
I am really confused why this is throwing me an error

**Comment by lilemark** [comment]
The syntax is:
```
{#findings}
{#category == 'web'}
{#cvssSeverity == 'Critical'}
{@cvssColor}
{cvssSeverity}

{identifier}

{title}

{@affected | convertHTML}
{/category == 'web'} {/cvssSeverity == 'Critical'}
{/findings}
```

And only this is the error: _Error: Closing tag does not match opening tag_

**Comment by relaxedricky** [comment]
Ok, based on the error and how you have your template, can you give this a try.  Swap:

`{/category == 'web'} {/cvssSeverity == 'Critical'}`

for:

```
{/category == 'web'}
{/cvssSeverity == 'Critical'}
```

**Comment by lilemark** [comment]
Yes, i tried that way but again is the same error

**Comment by relaxedricky** [comment]
I think I see the error. You have the following opening tags in this order:

```
{#findings}
{#category == 'web'}
{#cvssSeverity == 'Critical'}
```

Your closing tags are in the following order:

```
{/category == 'web'}
{/cvssSeverity == 'Critical'}
{/findings}
```

The issue is the order. I should have picked that up sooner based on the error:

> The tag "category == 'web'" is closed by the tag "cvssSeverity == 'Critical'"

Your second opening tag is `category `but the second closing tag you have is `cvssSeverity`.

Update the template to use:

```
{#findings}
{#category == 'web'}
{#cvssSeverity == 'Critical'}
{@cvssColor}
{cvssSeverity}

{identifier}

{title}

{@affected | convertHTML}
{/cvssSeverity == 'Critical'}
{/category == 'web'}
{/findings}
```

**Comment by lilemark** [comment]
Thank you, that worked perfectly :)
