### ISSUE TITLE
Can't get custom section working / not showing in template

### ISSUE THREAD

**Issue by schuesslerf** [pwndoc/pwndoc#171]
Hello,

so I'm trying to include an Executive Summary into my template, but I somehow can't get it to work, no matter what I try.. Propably just a little mistake, that I can't find..

So I downloaded the default template and basically just added the following underneath of "EXECUTIVE SUMMARY": 

`{-w:p summary.text}{@text | convertHTML}`

I then uploaded this Template to the Templates. I then created a Custom Section with the name "Executive Summary" and the field "summary". I then went to custom fields, selected the "Executive Summary" section and added an "Editor"-Component to it, with the label "text". I then created an audit type which uses this template.

However, when then trying to create an audit, I only get a message saying "undefined" (see image)...

![image](https://user-images.githubusercontent.com/10630224/128857412-12213cf2-472f-45b2-9f56-a8b245ce1bd0.png)

When I tried something else before (not exactly sure what, just played around), I also managed to not have that error, but still have nothing displayed in the word file...

Here are also some images of the settings and details:

![image](https://user-images.githubusercontent.com/10630224/128857760-0a09ba60-cfe8-4545-849b-d16944475f5e.png)

![image](https://user-images.githubusercontent.com/10630224/128857795-4e20c83f-1823-4d1a-9d81-a21a65c021c6.png)

![image](https://user-images.githubusercontent.com/10630224/128857818-6db3a4ed-ccdc-424f-9580-53afd1ac47b9.png)

![image](https://user-images.githubusercontent.com/10630224/128857850-ef37f4d6-2c33-42a5-a135-ec62663e4cf4.png)

![image](https://user-images.githubusercontent.com/10630224/128857885-1938c6a7-5a0a-4e4c-9fa1-0a6559a65434.png)

![image](https://user-images.githubusercontent.com/10630224/128857921-155a1808-979b-4b67-a137-a6e9f6b60235.png)

I'd really appreciate if you could help me out, getting this fixed, as I should get started using the tool asap...

Thanks in advance!

**Comment by schuesslerf** [comment]
Little edit: just made an update to have the newest version.. Error still persists, although now the message is "Internal Error", rather then  "undefined"...

**Comment by relaxedricky** [comment]
Hi,

Looking at the screenshots you have provided, it doesn't seem like you close off the tags using:

`{/summary.text}`

If you still see errors I would recommend reviewing the logs to help locate where the issue is:

`docker-compose logs -f pwndoc-backend`

**Comment by schuesslerf** [comment]
Okay, I chaned it to the following now:

![image](https://user-images.githubusercontent.com/10630224/128864978-bf5558a0-9255-48ac-8a01-9ed9237213ed.png)

Don't really fully understand the way the tags work tbh....

Thats the error I seem to get now:

```
 Error: Unclosed loop
pwndoc-backend     |     at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend     |     at getUnmatchedLoopException (/app/node_modules/docxtemplater/js/errors.js:221:13)
pwndoc-backend     |     at getPairs (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:87:15)
pwndoc-backend     |     at getPairs (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:68:22)
pwndoc-backend     |     at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:115:21)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend     |     at Object.postparse (/app/node_modules/docxtemplater/js/parser.js:95:19)
pwndoc-backend     |     at XmlTemplater.parse (/app/node_modules/docxtemplater/js/xml-templater.js:179:38)
pwndoc-backend     |     at Docxtemplater.compileFile (/app/node_modules/docxtemplater/js/docxtemplater.js:234:31)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/docxtemplater.js:305:18
pwndoc-backend     |     at Array.forEach (<anonymous>)
pwndoc-backend     |     at Docxtemplater.compile (/app/node_modules/docxtemplater/js/docxtemplater.js:303:27)
pwndoc-backend     |     at Docxtemplater.render (/app/node_modules/docxtemplater/js/docxtemplater.js:365:12)
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:77:13) {
pwndoc-backend     |   properties: {
pwndoc-backend     |     id: 'unclosed_loop',
pwndoc-backend     |     explanation: 'The loop with tag "summary" is unclosed',
pwndoc-backend     |     xtag: 'summary',
pwndoc-backend     |     offset: 662,
pwndoc-backend     |     file: 'word/document.xml'
pwndoc-backend     |   }
pwndoc-backend     | }
pwndoc-backend     | TypeError: Cannot read property 'substring' of undefined
pwndoc-backend     |     at /app/src/lib/report-generator.js:89:118
pwndoc-backend     |     at Array.map (<anonymous>)
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:88:59)
pwndoc-backend     |     at runMicrotasks (<anonymous>)
pwndoc-backend     |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
```

**Comment by relaxedricky** [comment]
I would recommend reading over the [docs](https://pwndoc.github.io/pwndoc/) further as well as the default template to get a better understanding. Though I think some things in the default template are now updated (only related to the executive summary).

The following lines show where the issue is:

```
pwndoc-backend     |   properties: {
pwndoc-backend     |     id: 'unclosed_loop',
pwndoc-backend     |     explanation: 'The loop with tag "summary" is unclosed',
pwndoc-backend     |     xtag: 'summary',
pwndoc-backend     |     offset: 662,
pwndoc-backend     |     file: 'word/document.xml'
pwndoc-backend     |   }
```

Can you update your template by removing `{#SUMMARY}`

**Comment by schuesslerf** [comment]
Yeah, i tried that as well now, so now it looks like that:

![image](https://user-images.githubusercontent.com/10630224/128865974-8c034b3e-ccdb-4570-9395-270f0601c1cb.png)

```
pwndoc-backend     | TypeError: Cannot read property 'substring' of undefined
pwndoc-backend     |     at /app/src/lib/report-generator.js:89:118
pwndoc-backend     |     at Array.map (<anonymous>)
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:88:59)
pwndoc-backend     |     at runMicrotasks (<anonymous>)
pwndoc-backend     |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
pwndoc-backend     | user nameless left room 6112e0b2b69f4a00188c5952
pwndoc-backend     | user nameless joined room 6112e114b69f4a00188c5956
pwndoc-backend     | Error: Raw tag should be the only text in paragraph
pwndoc-backend     |     at new XTTemplateError (/app/node_modules/docxtemplater/js/errors.js:24:16)
pwndoc-backend     |     at throwRawTagShouldBeOnlyTextInParagraph (/app/node_modules/docxtemplater/js/errors.js:205:13)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/modules/rawxml.js:34:7
pwndoc-backend     |     at Array.forEach (<anonymous>)
pwndoc-backend     |     at Object.getInner (/app/node_modules/docxtemplater/js/modules/rawxml.js:28:18)
pwndoc-backend     |     at expandOne (/app/node_modules/docxtemplater/js/traits.js:203:23)
pwndoc-backend     |     at Object.expandToOne (/app/node_modules/docxtemplater/js/traits.js:241:22)
pwndoc-backend     |     at RawXmlModule.postparse (/app/node_modules/docxtemplater/js/modules/rawxml.js:77:21)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend     |     at postparse (/app/node_modules/docxtemplater/js/parser.js:76:20)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:174:30
pwndoc-backend     |     at Array.reduce (<anonymous>)
pwndoc-backend     |     at Object.postparse (/app/node_modules/docxtemplater/js/modules/expand-pair-trait.js:154:32)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/parser.js:74:24 {
pwndoc-backend     |   properties: {
pwndoc-backend     |     id: 'raw_xml_tag_should_be_only_text_in_paragraph',
pwndoc-backend     |     explanation: 'The raw tag "text | convertHTML" should be the only text in this paragraph. This means that this tag should not be surrounded by any text or spaces.',
pwndoc-backend     |     xtag: 'text | convertHTML',
pwndoc-backend     |     offset: 681,
pwndoc-backend     |     paragraphParts: [
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object], [Object], [Object], [Object],
pwndoc-backend     |       [Object]
pwndoc-backend     |     ],
pwndoc-backend     |     file: 'word/document.xml'
pwndoc-backend     |   }
pwndoc-backend     | }
```

I basically checked all the docs but I don't really get how everything works.. As an example, the `{-w:p` appears multiple times in the doc, but it doesn't seem like its explained somewhere.. But back tot the probelm, now it says: `The raw tag "text | convertHTML" should be the only text in this paragraph. This means that this tag should not be surrounded by any text or spaces.` .... The only thing there is like in the screenshot above, so only

Executive Summary
{-w:p summary.text}{@text | convertHTML}{/summary.text} 

What else do I need to change? I also tried using only the `{@text | convertHTML}` part and then adding {#SUMMARY} and {/SUMMARY} around it, but didn't work either... What am I doing wrong?

**Comment by relaxedricky** [comment]
So the error you provided is outlining the issue:

> The raw tag "text | convertHTML" should be the only text in this paragraph. This means that this tag should not be surrounded by any text or spaces.

You have:

`{-w:p summary.text}{@text | convertHTML}{/summary.text}`

The above has `{@text | convertHTML}` surrounded by text, it isn't the only text in the paragraph, as stated by the error, it wants:

```
{-w:p summary.text}
{@text | convertHTML}
{/summary.text}
```

**Comment by schuesslerf** [comment]
Oh okay, so its really about the line break in that case... Understood... Thank you :) You propably could update your Doc a bit when it comes to the templating thing... understood now, though, thank you! 

Could you still explain me the use of `{-w:p` though? Its not explained anywhere in the docs... What does it mean?

**Comment by relaxedricky** [comment]
I will see if I can send a push request with some updates to the document, though I do want to point out that I do not own this tool/repo. I am simply a user of pwndoc user who tries to help when I see issues coming through,

In regards to your question, my understanding is the tool makes use of docxtemplater, if you have a at the following [url](https://docxtemplater.readthedocs.io/en/v3.22.5/tag_types.html#dash-syntax) you would see the following:

> With the Dash syntax you can specify the tag you want to loop on: For example, if you want to loop on paragraphs (w:p), so that each of the loop creates a new paragraph, you can write:
> {-w:p loop} {inner} {/loop}

**Comment by schuesslerf** [comment]
Okay, I see :) Thanks for your help already..

One last question to you (maybe you can help here as well): where do I find a documentation of the "convertDate" function?  As I'm German, I'd like to have the German date type here, so at the first page, instead of "Tuesday, August 10, 2021", I'd need somethink like "Dientsag, 10. August 2021" (so german name of day, and other order of day and month) and also, on the "organisation part" (start and end of the pentest), rather then something like "08/02/2021", I would need "02.08.2021"...

I can see, that in the template, theres `{date| convertDate: 'full'}` and `{date_start | convertDate: 'short'} `, but what do I need to change in order to have the dates like mentioned above?

**Comment by relaxedricky** [comment]
You are welcome.

In regards to the question, have you checked the documentation? I think I linked this earlier but I will put it [here](https://pwndoc.github.io/pwndoc/) for you as well.

**Comment by schuesslerf** [comment]
Got it, thank you! :)
