### ISSUE TITLE
Case Sensitivity Bug with Locale Value

### ISSUE THREAD

**Issue by UncleRaymondo** [pwndoc/pwndoc#174]
Hi,

Configuring the system per the guides shows the locale for English as "en". However when importing a yml file with vulnerabilities and the locale is "EN" they don't appear on the front end.

The fix in this instance was change the system language locale for English from "en" to "EN" and then reimporting, but this seems to be a very trivial and annoying bug that could cause many issues with missing vulnerabilities.

Appreciate a resolution at your earliest.

Cheers,
Ray

**Comment by yeln4ts** [comment]
It is case sensitive, you should either change the locale in your vulnerabilities yml file or in the GUI
