### ISSUE TITLE
Manual refresh before finding is added

### ISSUE THREAD

**Issue by Fopje** [pwndoc/pwndoc#176]
The 30th of August I did a clean installation of PwnDoc. Now when adding findings to an audit, I have to manually refresh the page before the finding appears in the menu on the left side.

![image](https://user-images.githubusercontent.com/4934752/131657796-d5ec8868-57be-43f5-ad12-4341198f95d5.png)

**Comment by yeln4ts** [comment]
This can happen if the server is restarted when you are on the Audit page because the websocket connection is lost

**Comment by Fopje** [comment]
> This can happen if the server is restarted when you are on the Audit page because the websocket connection is lost

I found the problem. I've changed the listening port from 8443:8443 to 443:8443, yet the socket still tries to connect to the old port:

![image](https://user-images.githubusercontent.com/4934752/131837484-d8631f4a-bd6d-4f8f-b297-fcb1e6286c04.png)

**Comment by Fopje** [comment]
Changed the API port from 8443 to 443 in pwndoc\frontend\quasar.conf.js
