### ISSUE TITLE
Re-arrange the findings orders

### ISSUE THREAD

**Issue by andrewli315** [pwndoc/pwndoc#177]
Are there any function/method to re-arrange the order of findings?
I want to sort or drag the findings but it seems not work. 
Thanks a lot.

**Comment by yeln4ts** [comment]
Can you specify what is not working ?
You can rearrange the order automatically or manually with the sorting button:
![image](https://user-images.githubusercontent.com/4255028/132547202-4ac8941f-a8f7-451f-9db6-e80f8d3bfefa.png)

The order in the GUI will be the order in the report

**Comment by andrewli315** [comment]
Thank you for help! Maybe my pwndoc version is out-to-date.

**Comment by yeln4ts** [comment]
This is a recent feature that has been implemented in the last release https://github.com/pwndoc/pwndoc/releases/tag/v0.4.0
