### ISSUE TITLE
Sorting by CVSS

### ISSUE THREAD

**Issue by litsnarf** [pwndoc/pwndoc#179]
Hi, 
when having multiple categories, in the report the findings seems to be sorted in first by category. This means that if i have two categories first all vulnerabilities for one category are sorted and then all vulnerabilities for the other category are sorted and added. So if i have something like this:
**Category 1** 
- issue 1: CVSS 10
- issue 2: CVSS 9

**Category 2** 
- issue 3: CVSS 9.5

the final sorting in the report will be

- issue 1: CVSS 10
- issue 2: CVSS 9 (this should be the last one)
- issue 3: CVSS 9.5

Is there a way to sort all vulnerabilities in all categories by CVSS (and not independently per category)?

**Comment by yeln4ts** [comment]
It is not possible right now but there was a pull request to add this feature #97 but it is a bit old and to many files have changed. I will surely add it in one of the next releases.

**Comment by litsnarf** [comment]
Ah OK. Thanks a lot for the reply and the great tool man!

**Comment by UbaidAhmed2803** [comment]
I was also looking for this feature. I hope this will soon be implemented. Keep up the good work.

**Comment by yeln4ts** [comment]
This is now implemented in the last commit with the `sortArrayByField` expression.
You can use it like this to sort by CVSS score descending:
```
{#findings | sortArrayByField: 'cvss.baseMetricScore': -1}
...
{/}
```
