### ISSUE TITLE
Chore: topic tags, versionning, documentation

### ISSUE THREAD

**Issue by noraj** [pwndoc/pwndoc#18]
1) add some tags to the project to help with referencement and search by topics, eg. for dradis:

![image](https://user-images.githubusercontent.com/16578570/93402969-817d4c80-f886-11ea-8d65-b88d8d700fb0.png)

I would add those tags:

- penetration-testing
- reporting
- reporting-tool
- pentest
- security-audit
- pentesting
- infosec
- collaboration
- collaborative
- vulnerability-library
- issue-library

2) Plans for git tags / release / changelog? :eyes: 

3) Plans to replace the github wiki with a  static documentation (eg. [some solutions](https://alternativeto.net/software/docsifyjs/)), that would allow better flexibility and collaborations. docsify.js is an easy choice as it's dynamically rendered from client side in JS. Other option are static website generators and would require a CI/CD to auto-build-n-deploy. Both choices can be self hosted with Github pages in the `docs/` folder.

**Comment by yeln4ts** [comment]
Thanks for the input.

1. I'll definitely add tags
2. I'll have to read about this but definitely want to add some kind of versioning. For now it's kind of almost v1.0
3. I looked at docsify.js and this seems like a good choice. I just started documentation but didn't have time to finish it but it's in the pipe

**Comment by noraj** [comment]
> I looked at docsify.js and this seems like a good choice. I just started documentation but didn't have time to finish it but it's in the pipe

A static doc would allow contribution to help you and make you save time 😉

**Comment by yeln4ts** [comment]
Added documentation and referencement tags.

**Comment by noraj** [comment]
> Plans for git tags / release / changelog? eyes

It would be useful to have a proper versioning using [semver](https://semver.org/). Each release would mean to create a git tag (`git tag -a vx.x.x` + `git push --follow-tags`), then a [github release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) including the changelog or a CHANGELOG.md file if your prefer to have it included in the repository and being independent from github (eg. mirror or migration to gitlab, reuse the file for the documentation staticgen, etc.).

I'm putting the subject on the table again because I feel that it would have been easier to identify a bug like #114 as already solved if there was a changelog or to keep track of new feature we may be unaware of.
