### ISSUE TITLE
Idea to change the image border feature to template level 

### ISSUE THREAD

**Issue by sl4cky** [pwndoc/pwndoc#185]
Hi, noticed that there is a border feature for images in the report, I would suggest this feature to be on template level since there can be templates with different designs and border designs.

**Comment by yeln4ts** [comment]
The border feature is for images only and cannot be on the template side because image tags are all replaced by raw Open Office XML at generation so it looses all its styling. I think a solid border with color options should cover most cases.

**Comment by sl4cky** [comment]
Thanks @yeln4ts
