### ISSUE TITLE
Add support for managing other users

### ISSUE THREAD

**Issue by JulianRunnels** [pwndoc/pwndoc#187]
This is an awesome tool for report writing, especially because multiple users can log into the same Audit. However, there is no functionality for user management, such as setting another user's permissions and passwords, or creating a new user. Can make it difficult to use in a team scenario. Would be nice if admins could manage that functionality from the GUI.

**Comment by relaxedricky** [comment]
If you select Data from the top nav menu and then select Collaborators on the left, you can be within the area of the application that allows for user management.

Here you can add new collaborators, set the password and permissions for current collaborators.

**Comment by JulianRunnels** [comment]
Oh wow i don't know how I missed that, thank you!
