### ISSUE TITLE
Custom filter for vulnType count?

### ISSUE THREAD

**Issue by crashboogie** [pwndoc/pwndoc#196]
Was trying to do a simple filter to get the count of vulnTypes and it doesn't seem to be working. Robbed the code straight from the count function already defined in the report-generator.js file. Some type of data type error that I'm not seeing/understanding?

**In the docx file:**
`Broken Access Control {findings | countVT: 'Broken Access Control'} `
&nbsp;

**Function in custom-generator.js:**
```
expressions.filters.countVT = function(input, vt) {
    if(!input) return input;
    var count = 0;

    for(var i = 0; i < input.length; i++){

        if(input[i].vulnType == vt){
            count += 1;
        }
    }

    return count;
}
```
&nbsp;

**Output from running `docker-compose logs -f pwndoc-backend`:**
```
pwndoc-backend     |   properties: {
pwndoc-backend     |     id: 'scopeparser_compilation_failed',
pwndoc-backend     |     offset: 2962,
pwndoc-backend     |     tag: "findings | countVT: 'Broken Access Control'",
pwndoc-backend     |     explanation: `The scope parser for the tag "findings | countVT: 'Broken Access Control'" failed to compile`,
pwndoc-backend     |     rootError: TypeError: Cannot read property '$stateful' of undefined
pwndoc-backend     |         at isStateless (/app/node_modules/angular-expressions/lib/parse.js:2942:13)
pwndoc-backend     |         at findConstantAndWatchExpressions (/app/node_modules/angular-expressions/lib/parse.js:3002:7)
pwndoc-backend     |         at /app/node_modules/angular-expressions/lib/parse.js:2953:5
pwndoc-backend     |         at forEach (/app/node_modules/angular-expressions/lib/parse.js:324:15)
pwndoc-backend     |         at findConstantAndWatchExpressions (/app/node_modules/angular-expressions/lib/parse.js:2952:4)
pwndoc-backend     |         at ASTCompiler.compile (/app/node_modules/angular-expressions/lib/parse.js:3113:3)
pwndoc-backend     |         at Parser.parse (/app/node_modules/angular-expressions/lib/parse.js:4181:27)
pwndoc-backend     |         at Object.compile (/app/node_modules/angular-expressions/lib/main.js:55:40)
pwndoc-backend     |         at Render.angularParser [as parser] (/app/src/lib/report-generator.js:198:30)
pwndoc-backend     |         at /app/node_modules/docxtemplater/js/modules/render.js:77:54
pwndoc-backend     |         at Array.forEach (<anonymous>)
pwndoc-backend     |         at Render.postparse (/app/node_modules/docxtemplater/js/modules/render.js:72:18)
pwndoc-backend     |         at /app/node_modules/docxtemplater/js/parser.js:74:24
pwndoc-backend     |         at Array.reduce (<anonymous>)
pwndoc-backend     |         at _postparse (/app/node_modules/docxtemplater/js/parser.js:73:22)
pwndoc-backend     |         at Object.postparse (/app/node_modules/docxtemplater/js/parser.js:95:19),
pwndoc-backend     |     file: 'word/document.xml'
pwndoc-backend     |   }
pwndoc-backend     | }
pwndoc-backend     | TypeError: Cannot read property 'substring' of undefined
pwndoc-backend     |     at /app/src/lib/report-generator.js:89:118
pwndoc-backend     |     at Array.map (<anonymous>)
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:88:59)
pwndoc-backend     |     at runMicrotasks (<anonymous>)
pwndoc-backend     |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
```

**Comment by BetaMaxHeadroom** [comment]
Can you please try lowercase + removing spaces from your template? https://pwndoc.github.io/pwndoc/#/docxtemplate?id=findings

**Comment by crashboogie** [comment]
Thanks for the suggestion! Unfortunately, I did try to use lowercase and removing spaces from the key as the docs suggest but it gave the same error. Even the standard count function in report-generator.js uses `if(input[i].cvss**S**everity === severity){`... so I figured the normal camelcase is the way to go for declaring those keys in the filters/functions.

I also tried to filter for `{findings | countVT: 'Broken'}` thinking that it didn't know how to interpret the spaces in the string to search for, but this gave the same error described above, so my suspicion is some kind of data type error but I cannot confirm.

**Comment by BetaMaxHeadroom** [comment]
Full disclosure, I made my template a long time ago. This may not work for you. I used a count function in the past, but no longer use it. What is in the template is:
`{findings | count: 'Critical'}, {findings | count: 'High'}, {findings | count: 'Medium'}, and {findings | count: 'Low'}`

When I go to https://localhost:7963/api/audits/, I see a few different things for _id. You may want to use some sort of json beautifier to view the page. But, if your setup is similar to mine, the first value for _id can be added to the end of https://localhost:7963/api/audits/ so that it looks like https://localhost:7963/api/audits/123idvalue. 

Some things that stand out to me are that I can't find anything for countVT. I have `vulnType` and `category` though. I could be way off since I haven't done this in so long. But, can you try `{findings | count: vulnType == 'Broken Access Control'}` in your template? If that works, but it also brings in a bunch of other vuln types, you might need to do a little !== for other vuln types. 

If that doesn't work, is there a way that I can get a copy of your template (please remove any branding)? Are you able to put something generic on your github?

**Comment by crashboogie** [comment]
ah, I think I know where the confusion is then. `countVT` is just the name I gave to the function that I put into `backend/src/lib/custom-generator.js`.

The reason I used that custom function in there is because the normal `count` function in `backend/src/lib/report-generator.js` that you described specifically looks at the `cvssSeverity` field, whereas I want the filter to get a count by the `vulnType` field.  So I essentially robbed the code straight from that standard count function in report-generator.js and just changed it to filter it by vulnType instead with that line above `if(input[i].vulnType == vt){`

I've already made another custom function in custom-generator.js that basically uses that count code but looks at a custom field I called `businessimpactscore`. That code works just fine and is below, but for some reason switching that line of  `if(input[i].businessimpactscore === severity){` to ` if(input[i].vulnType === severity){` breaks everything for some dumb reason.


```
// Count vulnerability by businessimpactscore
// Example: {findings | countBI: 'Critical'}
// Can use 'All' to get total
// Example: {findings | countBI: 'All'}
expressions.filters.countBI = function(input, severity) {
    if(!input) return input;
    var count = 0;

    for(var i = 0; i < input.length; i++){

        if(input[i].businessimpactscore === severity){
            count += 1;
        }
    }

	if(severity === 'All'){
		for(var i = 0; i < input.length; i++){
			if(input[i].businessimpactscore === 'Critical'){
				count += 1;
			}
			if(input[i].businessimpactscore === 'High'){
				count += 1;
			}
			if(input[i].businessimpactscore === 'Medium'){
				count += 1;
			}
			if(input[i].businessimpactscore === 'Low'){
				count += 1;
			}
		}
	}

    return count;
}
```

So using the function above, putting this into my docx template gives me the count of the business impact scores.
```
{findings | countBI: 'Critical'} Critical
{findings | countBI: 'High'}  High
{findings | countBI: 'Medium'}  Medium
{findings | countBI: 'Low'}  Low
```

and I did try that `{findings | count: vulnType == 'Broken Access Control'}` line in my docx template, but unfortunately returned a 0 despite having Broken Access Control entries in my audit. Makes sense if that count function is looking at cvssSeverity though.

I tried to access the api endpoint you mentioned as well but I couldn't access. I might need to tinker on that a bit.

**Comment by xpelican** [comment]
Hi, sorry to necro a closed thread, but has anyone found any way to make this happen?

crashboogie is right, the normal `count `function in `backend/src/lib/report-generator.js` ony looks at the `cvssSeverity` field, while the goal here is to get a count by the `vulnType` field.

I tried `{findings | count: vulnType == 'web'}`, as well as tried copying crashboogie's custom code and playing around with it, but could not get it to work. Anyone have any ideas?
