### ISSUE TITLE
Nmap import question ?

### ISSUE THREAD

**Issue by 0x4b61726361** [pwndoc/pwndoc#2]
Hello, thanks for your work ! I wonder when importing nmap scans if there is a simple way to retrieve all the hosts and services discovered that has been imported into an Audit ? Either for the GUI or from the API?

Thnaks by advance for your answer !

**Comment by yeln4ts** [comment]
Hello, when you import nmap or nessus scans, they are only imported client-side in your browser. Only the ones assigned to a scope are saved in the database and can be retrieved via the backend API: "/api/audits/<auditId>/network"
