### ISSUE TITLE
scope field

### ISSUE THREAD

**Issue by littlestewart** [pwndoc/pwndoc#20]
Hi,

the Scope field wont save my details !? This is the only field that i have a problem with..

**Comment by yeln4ts** [comment]
You have to press Enter since it's an input with multiple chips:
![image](https://user-images.githubusercontent.com/4255028/94021120-ac353c80-fd81-11ea-90c1-e51376bf0bf2.png)

**Comment by littlestewart** [comment]
Ok thanks i will test it
