### ISSUE TITLE
Error durring raport generation ` undefined (reading 'id')`

### ISSUE THREAD

**Issue by Serizao** [pwndoc/pwndoc#204]
Hello,

Thanks for your project it is wonder wonderful :) 

i have a problem during the raport generation :

```
pwndoc-backend     | TypeError: Cannot read properties of undefined (reading 'id')
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:80:30)
pwndoc-backend     |     at runMicrotasks (<anonymous>)
pwndoc-backend     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
```
when i add `console.log(error)` on `/app/src/lib/report-generator.js:80` because one of problems seem come from this lign:

`      if (error.properties.id !== 'undefined' && error.properties.id === 'multi_error') {`: /app/src/lib/report-generator.js:80

```
pwndoc-backend     | ReferenceError: border is not defined
pwndoc-backend     |     at ImageModule.getRenderedPartDocx (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:210:71)
pwndoc-backend     |     at ImageModule.getRenderedPart (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:189:20)
pwndoc-backend     |     at ImageModule.render (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:143:16)
pwndoc-backend     |     at moduleRender (/app/node_modules/docxtemplater/js/render.js:14:30)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/render.js:44:26
pwndoc-backend     |     at Array.map (<anonymous>)
pwndoc-backend     |     at render (/app/node_modules/docxtemplater/js/render.js:42:24)
pwndoc-backend     |     at XmlTemplater.render (/app/node_modules/docxtemplater/js/xml-templater.js:256:22)
pwndoc-backend     |     at /app/node_modules/docxtemplater/js/docxtemplater.js:386:21
pwndoc-backend     |     at Array.forEach (<anonymous>)
pwndoc-backend     |     at Docxtemplater.render (/app/node_modules/docxtemplater/js/docxtemplater.js:380:32)
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:77:13)
pwndoc-backend     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
pwndoc-backend     | TypeError: Cannot read properties of undefined (reading 'id')
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:81:30)
pwndoc-backend     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
```
i not understand why i try with the latest version with a modification else impossible tu build docker #203 i use the default template to generate report 

Do you know why ?

**Comment by forced-request** [comment]
I'm having a similar problem related to `borders`. This error only occurs when I try to include images in any of the fields. To be clear, I can create a report with no issues as long as I don't include any images. I have tried with both the default template and my custom template.

```
TypeError: Cannot read properties of undefined (reading 'substring')
    at /app/src/lib/report-generator.js:89:118
    at Array.map (<anonymous>)
    at Object.generateDoc (/app/src/lib/report-generator.js:88:59)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/src/routes/audit.js:387:29
ReferenceError: border is not defined
    at ImageModule.getRenderedPartDocx (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:210:71)
    at ImageModule.getRenderedPart (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:189:20)
    at ImageModule.render (/app/node_modules/docxtemplater-image-module-pwndoc/js/index.js:143:16)
    at moduleRender (/app/node_modules/docxtemplater/js/render.js:14:30)
    at /app/node_modules/docxtemplater/js/render.js:44:26
    at Array.map (<anonymous>)
```

**Comment by C0wnuts** [comment]
Hello,

I have the same error as @Serizao but I think I was able to locate the problem. When I add a company in the general information,  I get an error. When I remove it I can generate the docx.

logs :
```pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
pwndoc-backend     | TypeError: Cannot read properties of undefined (reading 'id')
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:80:30)
pwndoc-backend     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
pwndoc-backend     |     at async /app/src/routes/audit.js:387:29
```

Reproduction approach:
1. Create a new audit report
2. Fill in the general audit information
3. Add a company
4. Generate = error
5. Remove company from general information + generate = OK

**Comment by J0k3r111** [comment]
Same error here after version update.
not only company field generates this error, any other not numeric parameter set in general fields causes same behavior.

**Comment by Serizao** [comment]
I found the solution to make it work temporarily even though I don't understand why it does that:

the function of line 208 of the file `/app/node_modules/docxtemplater-image-module-pwndoc/js` is like this:
`getRenderedPartDocx(rId, size, centered)`
when it should be like this :
`getRenderedPartDocx(rId, size, centered, border)`


In the source code of the repo (https://github.com/pwndoc/docxtemplater-image-module-pwndoc/blob/master/js/index.js#L209) it seems to be correctly implemented so I do not understand
![image](https://user-images.githubusercontent.com/11671895/140934430-08d858cc-d740-4dff-8afc-023b0ac1467d.png)

**Comment by J0k3r111** [comment]
can confirm that the fix provided 

> I found the solution to make it work temporarily even though I don't understand why it does that:
> 
> the function of line 208 of the file `/app/node_modules/docxtemplater-image-module-pwndoc/js` is like this: `getRenderedPartDocx(rId, size, centered)` when it should be like this : `getRenderedPartDocx(rId, size, centered, border)`
> 
> In the source code of the repo (https://github.com/pwndoc/docxtemplater-image-module-pwndoc/blob/master/js/index.js#L209) it seems to be correctly implemented so I do not understand ![image](https://user-images.githubusercontent.com/11671895/140934430-08d858cc-d740-4dff-8afc-023b0ac1467d.png)

Can confirm that this solution worked for me as well, thank you!

**Comment by wannabeslime** [comment]
> I found the solution to make it work temporarily even though I don't understand why it does that:
> 
> the function of line 208 of the file `/app/node_modules/docxtemplater-image-module-pwndoc/js` is like this: `getRenderedPartDocx(rId, size, centered)` when it should be like this : `getRenderedPartDocx(rId, size, centered, border)`
> 
> In the source code of the repo (https://github.com/pwndoc/docxtemplater-image-module-pwndoc/blob/master/js/index.js#L209) it seems to be correctly implemented so I do not understand

line 5833 & 23404 of the file `pwndoc/backend/package-lock.json` is like :
`"version": "git+ssh://git@github.com/pwndoc/docxtemplater-image-module-pwndoc.git#81776cc5383fb6e5d02d3ad3ffc818c362be7688"`
and it seems references older one.
So, in my case, i changed these line to `"version": "git+ssh://git@github.com/pwndoc/docxtemplater-image-module-pwndoc.git"` (or latest one: `#05451c6302d7ffa97767c41db3b608f074a872e6`) and it worked. (At least now)
I hope this helps something.
