### ISSUE TITLE
undefined error when generating report

### ISSUE THREAD

**Issue by littlestewart** [pwndoc/pwndoc#21]
When i add my first finding and i try to generate the report to see the result into the report by exemple, i get an UNDEFINED ERROR IN RED AT THE TOP OF PWNDOC. But when i remove the finding it is working..
![undefined](https://user-images.githubusercontent.com/71742137/93958266-2505ab80-fd24-11ea-8bdd-d580d30a5422.PNG)

**Comment by littlestewart** [comment]
Ok so did you find something i the template that was causing the problem ?

**Comment by yeln4ts** [comment]
The template was old, at this time findings fields were only text but I changed them to HTML and didn't update the default template (this is not the template I use so forgot to update it)
