### ISSUE TITLE
Migrate entire pwndoc instance to new host

### ISSUE THREAD

**Issue by DeepFri3d** [pwndoc/pwndoc#219]
Hi there,

Is there a simple method for moving across existing reports in progress from one system to another?  Wondering if it's a simple case of replacing the fresh install folder with the existing one, or would it require a full container migration from Docker.

Many thanks

**Comment by yeln4ts** [comment]
Hi,

You can just copy the `backend/mongo-data`, `backend/report-templates` and `backend/src/config` folders to your new instance.
