### ISSUE TITLE
Sort exceeded memory limit

### ISSUE THREAD

**Issue by se-fLa** [pwndoc/pwndoc#222]
Having trouble with the following error:

```
(node:17) UnhandledPromiseRejectionWarning: MongoError: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.
    at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:261:20)
    at MessageStream.emit (events.js:189:13)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at MessageStream.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:667:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

It looks like setting `{allowDiskUse: true}` would resolve it but I can not find the aggregate call where it should be.

Please advice what i can do as it is currently not possible to add new findings to the audit with this error.

**Comment by yeln4ts** [comment]
How many findings do you have (and categories) ?
What commit version do you have ?

**Comment by se-fLa** [comment]
I have 31 findings in 3 categories.

The error happens when I try to add a new finding. The next created finding would be 32nd.
I can edit existing ones but not add new ones.

There are about 48 pictures in the PROOFS sections, some have none some have 5-6 images. Image size varies from 5K to 270K each.

If I generate docx report it becomes 4.4MB

I was running commit version edfec1e5d98b3163499d937d04d4d5a280c4ccfc from Jan 15 when I got this but have tried to upgrade with latest version today and get the same error  with commit version e47a2dfdb5d0303379633bed6cb95e15e431cb13. 

With the latest version I had to change 
```
backend/docker-compose.dev.yml:    image: mongo:4.2.15
docker-compose.yml:    image: mongo:4.2.15

```
to 

```
backend/docker-compose.dev.yml:    image: mongo
docker-compose.yml:    image: mongo

```
to get rid of this fault:

`E  STORAGE  [initandlisten] WiredTiger error (-31802) [1638449223:292092][1:0x7f078e774b00], connection: __log_open_verify, 925: unsupported WiredTiger file version: this build only supports versions up to 4, and the file is version 5: WT_ERROR: non-specific WiredTiger error Raw: [1638449223:292092][1:0x7f078e774b00], connection: __log_open_verify, 925: unsupported WiredTiger file version: this build only supports versions up to 4, and the file is version 5: WT_ERROR: non-specific WiredTiger error
`

**Comment by yeln4ts** [comment]
Between the 2 commits the sorting of the findings changed. This is from before:
![image](https://user-images.githubusercontent.com/4255028/144635254-98b88758-c9eb-4576-84eb-74cf80c72d32.png)
I could understand the issue with this but now the sorting is done manually so I think maybe you did not rebuild properly.
Can you check in your container that you have the updated version ?
`docker exec -it pwndoc-backend /bin/sh` and then check the file `src/models/audit.js` for the function `createFinding`

**Comment by se-fLa** [comment]
I cleaned up the whole system, prun'ed all images and rebuilt everything from scratch without cache. I still have to change the `mongo:4.2.15` to `mongo` but now it works yes, the memory issue is resolved with the new version.
Thank you.
However, now I can not add Customer Sections to my report, there is no button to add them. (Previously added are present). Might be a issue from the migrated database maybe?

**Comment by yeln4ts** [comment]
Ok perfect.
Regarding mongo there has been changes at some point I don't know how to handle an easy migration between the 2 versions. There is a repair command that worked when I tested it: https://github.com/pwndoc/pwndoc/issues/155#issuecomment-885149794
 
For the Custom Sections they must be defined in the Audit Type since v0.2.0. You can check the Changelogs: https://github.com/pwndoc/pwndoc/releases
