### ISSUE TITLE
RangeError: Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by chemoms** [pwndoc/pwndoc#223]
Thanks for this awesome tool!  

I just updated everything and attempting to generate a report (me too :-)) 

I get the following now:

![pwndocerror](https://user-images.githubusercontent.com/71432464/144611995-dd2cec78-8d8e-4007-9eff-3aeac0a8c3c2.png)

**Comment by yeln4ts** [comment]
Thanks I think I found the issue and will commit the fix soon. Can you confirm that you have scopes defined in the Network section ?
Meanwhile if you want to test it try to update this line in the `backend/src/lib/report-generator` : 
![image](https://user-images.githubusercontent.com/4255028/144636197-8db0cf18-0e81-41b0-b0e1-c601275b1a04.png)

**Comment by chemoms** [comment]
Hello @yeln4ts !

Thanks, it's working now ! :-)
