### ISSUE TITLE
List Paragraph is presented right to left

### ISSUE THREAD

**Issue by sl4cky** [pwndoc/pwndoc#228]
When adding a bullet list to any html editor, it is presented in right to left mode in the report. I have tried to change the style of List Paragraph but it doesn't help.

**Comment by yeln4ts** [comment]
Did you follow the documentation for setting up the correct numbering styles ? https://pwndoc.github.io/pwndoc/#/docxtemplate?id=styles

**Comment by sl4cky** [comment]
I figured it out, I had to create a total new template, there was some kind of bug in word styling.
