### ISSUE TITLE
Exporting report with findings without categories 

### ISSUE THREAD

**Issue by sl4cky** [pwndoc/pwndoc#232]
For example, when doing a mobile penetration test, we have also findings which is categorized as web application findings or network findings, and when adding them they are categorized, and also when printing them in the report they are also categorized, how can we print the findings in the report categorized according to severity level with all categories and not sorted according to category? 

Thanks.

**Comment by yeln4ts** [comment]
Categories should be a higher level sorting. It is meant to separate your findings in different sections. For your use case you should use Vulnerability Type to define a vulnerability as web app, mobile, network, etc
If you don't have usage of Categories you don't have to use it.

**Comment by sl4cky** [comment]
I would see category as a finding category for example web, mobile, network etc.. and vulnerability type as something more specific like authentication, authorization, etc... is there any way to see to choose the categories/vulnerability types and still print them without any category sorting in the report? If this is not an option how can I change it in the code? 

Thanks.

**Comment by yeln4ts** [comment]
You could use web, mobile, network, etc as vulnerability types and create a custom field for your more specific stuff like authentication, authorization, etc (and not use Categories). You will then have everything under `No Category` and will be able to achieve what you want.
