### ISSUE TITLE
Unable to get custom section to show in document

### ISSUE THREAD

**Issue by rayaar** [pwndoc/pwndoc#233]
I am unable to get any custom sections to print in my documents. I have followed the documentation as close as I can, but for some reason the section will not apear.

I have created a custom section like this:

![image](https://user-images.githubusercontent.com/6630936/148555226-ac69fbce-e619-4f15-86a7-2b98770bd3a1.png)

And added a custom field to that section like this:
![image](https://user-images.githubusercontent.com/6630936/148555509-bbccf42e-1991-42e9-b2f5-06bf45c4d6bb.png)

And added some text and an image in the section under an audit
![image](https://user-images.githubusercontent.com/6630936/148555845-12d0c32a-dc03-462b-aa75-1c961de0f3b1.png)

but with the example from the documentation
`
{ mtest.name}
{-w:p mtest.text}{@text | convertHTML}
{-w:p images}{%image}
Image 1 - {caption}
{/images}
{/mtest.text}
`

I only get the {mtest.name} to work, while the rest prints empty lines.
![image](https://user-images.githubusercontent.com/6630936/148556277-a0bdfb1d-eaf1-4260-a8fd-a5274be40ad5.png)

I really feel I have tried everything, so some guidance would be amazing. 

Is there like a discord channel or something where I could ask for help?

**Comment by yeln4ts** [comment]
Hello try this:
`{ mtest.name} {-w:p mtest.label}{@text | convertHTML} {-w:p images}{%image} Image 1 - {caption} {/images} {/mtest.label}`

I will focus on updating the documentation soon since some things changed. In your case you should use the label name instead of text

**Comment by rayaar** [comment]
That worked beautifully. Thanks a bunch!
