### ISSUE TITLE
undefined cvss score

### ISSUE THREAD

**Issue by AlrikRr** [pwndoc/pwndoc#235]
Hello ! First of all, thank you for this amazing tool !

I didn't see any post regarding my issue so there it is !
 
I have an issue regarding the CVSS score when generating the repport.

Here is my configuration :
- Just install pwndoc in my Kali linux (updated)
- Using default docx from documentation, not edited
- Added two local (en and fr ) but I only use EN for now
- Created an audit Type with the default template for both EN and FR

For the audit here is the config : 
![image](https://user-images.githubusercontent.com/32389491/148817601-e3b90b59-6255-42ff-b95c-0b5c1fc084ac.png)

and for this audit I have 2 vulnerabilities : 

One with LOW CVSS 2.9
![image](https://user-images.githubusercontent.com/32389491/148817778-f4d8f1cf-cbc1-46c6-bab5-d2141aebaabf.png)

And the other one is HIGH with 7.3
![image](https://user-images.githubusercontent.com/32389491/148817906-b22b4f3f-a74e-45e0-b0a5-e832bf18eb02.png)

So, the problem is when I generate the repport, I don't see the CVSS score, it is written as undefined. 

The summary vuln : 
![image](https://user-images.githubusercontent.com/32389491/148818151-cfaf8553-32e0-4cb7-a7d3-73f9c7ac6c3a.png)

and the vulns : 
![image](https://user-images.githubusercontent.com/32389491/148818226-6234a07b-dd68-4887-90db-e29e7acb30c9.png)
![image](https://user-images.githubusercontent.com/32389491/148818260-34b67375-183a-494d-89c9-bf98cb59fdf4.png)

I don't really know where the problem is since i'm using the default docx template
I tried few other configuration like editing the local and using FR for the vulns and the template but nothing work. Everytime the CVSS score is not here.

I also tried to add the default findings in [https://pwndoc.github.io/pwndoc/#/docxtemplate?id=findings](https://pwndoc.github.io/pwndoc/#/docxtemplate?id=findings) 
but nothing : 
![image](https://user-images.githubusercontent.com/32389491/148819257-5be604b3-6666-4a0d-ab6e-14bd55223c09.png)

Thank you for your time !

More Screen of the config : 
![image](https://user-images.githubusercontent.com/32389491/148819625-fa670338-2906-4bda-9916-5a0fbe8063c0.png)

![image](https://user-images.githubusercontent.com/32389491/148819668-c28c272b-45c7-4d3d-81de-ea6597e4eab8.png)

![image](https://user-images.githubusercontent.com/32389491/148819733-a636af95-2ccd-405a-8b29-e9932e2d6148.png)

![image](https://user-images.githubusercontent.com/32389491/148819859-505421cd-857d-4833-9c99-61ab4c1285d4.png)

**Comment by yeln4ts** [comment]
Hello, I updated the CVSS data in the last release and forgot to update the template accordingly to the release Changelog.
You have to change this in your template:
![image](https://user-images.githubusercontent.com/4255028/148832890-bc11e36a-770a-45ed-b3c3-7d6dedc1fc5d.png)

**Comment by AlrikRr** [comment]
My bad ! Didn't read the Update ...
Thank you ! Work like a charm !
