### ISSUE TITLE
help plz: dynamically categories

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc/pwndoc#239]
I noticed the following in changelog 0.5.0:

> Add "categories" data available in report template to generate findings dynamically by Category: categories: {categoryName:<name>, categoryFindings:<[Array of Findings]>}

I did try messing around with this in a template but wasn't having much luck, so wondered if anyone could help out.

Ideally, I would like to have things generated dynamically. So as an example, IF the report contains issues within the "mobile" category then a header for this section of the test is created containing just these issues. Overall allowing the template to have coded sections for all possible categories but they are only created IF vulnerabilities within these categories are found.

**Comment by yeln4ts** [comment]
This is already how it works.
At the report generation, it will add a `categories` field based on findings of the Audit so that only used categories are present.
In the template you would do the following:
```
{#categories}
{categoryName} (Header)
{#categoryFindings}
... same thing as before ...
{/categoryFindings}
{/categories}
```

**Comment by relaxedricky** [comment]
I must have been lacking sleep as before I couldn't get the syntax right, thank you for the example. Works perfectly.
Nice work.
