### ISSUE TITLE
Vulnerability ID / Reference code

### ISSUE THREAD

**Issue by noraj** [pwndoc/pwndoc#24]
I suggest to add one field to vulnerabilities: a vulnerability ID a.k.a. internal reference or reference code.

For **example**, if your company is named Example, you would like to have a vulnerability ID looking like EXA-XXXXX. So each vulnerability has its own ID, eg. EXA-00001, EXA-00002.

**Why**? Having a unique ID for each vulnerability help to refer to them in a way that doesn't change over time. Else people add an ID like Vuln-0001 using the order of discovery or sorted by severity but that change from one pentest to another.

It doesn't need to be auto-incremental, just a free varchar so people can use different ID structure for different type of vulns, eg. AUTH-001, INJ-001, etc.

**Comment by yeln4ts** [comment]
I don't really see the necessity of this or don't know in what context it would be used. But anyway you could do this by creating a Category with an additional field «VulnID» for example. Categories allow to have great customization over Vulnerabilities.

**Comment by noraj** [comment]
> But anyway you could do this by creating a Category with an additional field «VulnID» for example. Categories allow to have great customization over Vulnerabilities.

I didn't know it was possible to create fields for Categories, I just discovered it: https://pwndoc.github.io/pwndoc/#/data?id=vulnerability-categories, teh way you have to create them is a little hidden. I tested, it seems to answer my question but I saw that the new field are present only for new vulnerabilities, the field does not appear for vulns created before the field was created. This also raise a question, will the field stay on vulnerabilities after the field was removed fro ma category?

**Comment by yeln4ts** [comment]
You can change the Category of the Vulnerability when you edit one (in the toolbar of the modal), it will add the field(s) of the Category.
Custom Data are just helpers to create vulnerabilities/audit, there is no database relation between them so once it's created it won't be changed if you change a Custom Data. So no if you update/delete the category it won't affect vulnerabilities.

**Comment by noraj** [comment]
Ok I think I can close this for now :) Thx for the info
