### ISSUE TITLE
Dissapearing elements in the sidebar when editing audits

### ISSUE THREAD

**Issue by appstrike** [pwndoc/pwndoc#241]
After a fresh install on the latest release (from 12th Jan), I went and created an audit. When loading the page I can see "Network Scans" and "Findings" in the sidebar, for a split second, but then they dissapear and the page looks like this:

![image](https://user-images.githubusercontent.com/96656932/149617407-8fb0df4e-3746-4664-8cb9-aeb156a954a3.png)

I can't add any findings as a result of this. Any ideas?

**Comment by relaxedricky** [comment]
When creating the audit in custom data, did you tick the boxes for "Network Scans" and "Findings"?

**Comment by appstrike** [comment]
Yes, I did: 

![image](https://user-images.githubusercontent.com/96656932/149621660-bc97bc7a-bb58-46c8-baed-bd7f706ede69.png)

**Comment by appstrike** [comment]
Oh my it was my mistake... Just saw in the image that I have selected to hide the sections. 

![image](https://user-images.githubusercontent.com/96656932/149621660-bc97bc7a-bb58-46c8-baed-bd7f706ede69.png)

Once I made a new audit and with the new type of audit it all was working.. 

Thank you @relaxedricky !
