### ISSUE TITLE
Pagebreak

### ISSUE THREAD

**Issue by sl4cky** [pwndoc/pwndoc#246]
Hey, how can I add page breaks between each finding so that each finding will move to a new page?

**Comment by paul1278** [comment]
I did it using a pagebreak before the headline of the finding, like this:
```
{#findings}
[wordPageBreak (under insert)]
{title (on new page)}
....

{/findings}
```

**Comment by sl4cky** [comment]
I just added a page brake after each of the findings before the closing tag and that worked, thanks
