### ISSUE TITLE
Addition: adding more customer related information

### ISSUE THREAD

**Issue by Fopje** [pwndoc/pwndoc#247]
At the moment in de list of companies you can only add a logo besides the company name. It would be a nice addition (in my opinion) to be able to include address details as such.

**Comment by paul1278** [comment]
I agree, do you know any more attributes? Address would be nice.

Phone etc. is stored inside clients, so I guess those are maybe not required?

**Comment by paul1278** [comment]
Do you have ideas for any more attributes? Address would be nice.

Phone etc. is stored inside clients, so I guess those are maybe not required?

**Comment by paul1278** [comment]
Company shortname as mentioned in #175

**Comment by yeln4ts** [comment]
shortname was added to comany model
