### ISSUE TITLE
German Date Localization Question

### ISSUE THREAD

**Issue by sectester22** [pwndoc/pwndoc#252]
Hello,
I started using pwndoc now for some time and really dig it. I made my own word template but I have a problem with the date.
When I convert the date into the german localization using the command **{date | convertDateLocale: 'de-DE':'short'}** in the word template the single digits in Day and Month don't show a zero before the number.

For example it will show as: 5.1.2022 
Should be shown as : 05.01.2022 

Am I doing something wrong or is it possible to fix this? 
Because normally the date in german is noted with a zero before the single digit days and months. 

Thank you in Advance!

**Comment by paul1278** [comment]
Is this the exact syntax you are using? And the newest version? It works on my side with your command

**Comment by sectester22** [comment]
Hello, thank you for your reply. 
I could see the system had some problems updating to the newest version. I updated it. Still It has this Issue. 
Then I reinstalled it on a clean Debian and there it worked. So I think it might be some problem on my side of the Hostsystem. 
Sorry for the Inconvenience but thank you for the help! :D
