### ISSUE TITLE
Bug: {cvssv3} no longer work

### ISSUE THREAD

**Issue by Zeecka** [pwndoc/pwndoc#254]
The {cvssv3} field no longer work. I eddited the default template for my tests :

![image](https://user-images.githubusercontent.com/24873615/151802369-b65dcf77-368d-4cf9-a212-dc901c4e758d.png)

Note that cvss.baseMetricScore, cvss.cellColor and and cvssObj works well.

**Comment by relaxedricky** [comment]
Hey,

As of version 0.5.0 (2022-01-06):

- Changes to CVSS data require to update Word templates to avoid report generation errors
    - Replace `{cvssv3}` by `{cvss.vectorString}`
    - Replace `{cvssScore}` by `{cvss.baseMetricScore}`
    - Replace `{cvssSeverity}` by `{cvss.baseSeverity}`
    - Replace `{@cvssColor}` by `{@cvss.cellColor}`

**Comment by Zeecka** [comment]
My bad, I had a look at the documentation but not the changelog. Thank you :) .
