### ISSUE TITLE
How to show CustomSectionFields in report

### ISSUE THREAD

**Issue by br33z3** [pwndoc/pwndoc#255]
![image](https://user-images.githubusercontent.com/31792851/152076941-7ab654f2-c316-4531-84e4-1a04b31874ce.png)

![image](https://user-images.githubusercontent.com/31792851/152076979-e8afba68-bab3-477a-97e7-23421bf81e00.png)

![image](https://user-images.githubusercontent.com/31792851/152077007-44967b5f-6e23-436b-9bbf-e6620637f266.png)

How I can show the option that I select when I writing the report

**Comment by AnotherWayIn** [comment]
i'm struggling with this too. I'd like a list of custom recommendations from each issue to appear in the exec summary as a bullet list. btw thanks for taking the time to write this. it's awesome. i've been able to migrate my company report template over in a matter of hours and replace all the macros too using your well-explained documentation.

![image](https://user-images.githubusercontent.com/10500665/152111672-5ccff2f6-8202-447e-815a-83b84c127d1e.png)

![image](https://user-images.githubusercontent.com/10500665/152111708-5d4ae726-181d-49c4-a7df-81beb5ef3ec8.png)

**Comment by br33z3** [comment]
So the solution you provide is not working right so we need to wait for an update :)

**Comment by paul1278** [comment]
@br33z3 have you tried writing the variables from your first example all lowercase? E.g. instead of `{TestType}` use `{testtype}`. Works this way for me with the current version.

@AnotherWayIn you are using a simple text-field, I think then you cannot use the loop-syntax using `{#}...`, just use `{exec_summary_recommendation}`.
I am using such a summary field using the editor-type (not the plaintext single line type). Then you can write it like this:
```
{#summary}
{@text | convertHTML}
{/summary}
```

**Comment by br33z3** [comment]
> @br33z3 have you tried writing the variables from your first example all lowercase? E.g. instead of `{TestType}` use `{testtype}`. Works this way for me with the current version. According to the docs it is always the lowercase label without spaces.
> 
> @AnotherWayIn you are using a simple text-field, I think then you cannot use the loop-syntax using `{#}...`, maybe just use `{exec_summary_recommendation}`. I am using such a summary field using the editor-type (not the plaintext single line type). Then you can write it like this:
> 
> ```
> {#summary}
> {@text | convertHTML}
> {/summary}
> ```

Wow thank you thats worked nice.
Also I wonder I want to add custom selection for vulnerabilities.
How I add this in report
![image](https://user-images.githubusercontent.com/31792851/152343150-5a1bd485-765c-4aaf-848c-417807852612.png)

There is no custom field in here.
![image](https://user-images.githubusercontent.com/31792851/152343343-e38d23e0-3091-4aea-ba89-800011709566.png)

**Comment by br33z3** [comment]
How can I show vulnerability based custom field in report.

![image](https://user-images.githubusercontent.com/31792851/152344741-6acdf626-5720-4584-880f-e7d124f48815.png)
![image](https://user-images.githubusercontent.com/31792851/152344803-d38ccdaf-7d27-4eb5-b9d8-9783d7b58791.png)
![image](https://user-images.githubusercontent.com/31792851/152344815-b159c594-4537-49dc-8978-9edcc8a4f384.png)

**Comment by paul1278** [comment]
You are using a text editor-field here, use a simple text field or write it using a filter as mentioned earlier:
```
{#port}
{@text | convertHTML}
{/port}
```

**Comment by br33z3** [comment]
Dude OMG you are my savior :) love u so much :)

**Comment by paul1278** [comment]
@br33z3 Youre welcome ;D

**Comment by br33z3** [comment]
I there any place that I can add you :D

**Comment by paul1278** [comment]
Currently not, besides on GitHub xD

**Comment by br33z3** [comment]
ahahhaaha. Thank you so much I am closing the issue.
Best regards my dear savior paul1278 <3
