### ISSUE TITLE
new checklist option

### ISSUE THREAD

**Issue by AnotherWayIn** [pwndoc/pwndoc#258]
Hi,

Any chance we can have other options added to checklists pls like a tick, cross and n/a?
thanks :)

**Comment by yeln4ts** [comment]
What do you mean by checklists ? I don't really understand what you want ?
Maybe you cloud provide a simple example of what you mean.

**Comment by AnotherWayIn** [comment]
sure, so ticking boxes is great, but sometimes i want to be able to put pass/fail and n/a like a compliance checklist for example:
![image](https://user-images.githubusercontent.com/10500665/153291556-cb7abe3d-b79f-446b-a563-8994e2a0b6b1.png)
thankyou!

**Comment by yeln4ts** [comment]
Oh ok I understand better now. 
Checkboxes will result in an array containing what you checked, so it is either in the array or not. It is supposed to represent a multiple selection.
For what you need to achieve, for now you can use the select component like this:
![image](https://user-images.githubusercontent.com/4255028/153448156-4e72b54d-e4c9-4dcf-ab92-a8f759850c1b.png)
This is less sexy but you will be able to achieve what you want.
I will however think about your idea for a future checklist component with an array of 3 states checkboxes

**Comment by m6sec** [comment]
A like the idea of a checklist to improve consistency across colaborators and would suggest multiple possible states for a checklist item 'Passed, Warning, Failed, Not Applicable'.

**Comment by yeln4ts** [comment]
After much thinking, using multiple states using checkboxes would be too confusing.
The better way to handle this would be to use select or radio components like this:
![image](https://user-images.githubusercontent.com/4255028/174666465-d590340e-a4a0-43cc-a19b-bcbff4ecf592.png)
