### ISSUE TITLE
request for custom descriptions to be presented in UI rather than field names

### ISSUE THREAD

**Issue by AnotherWayIn** [pwndoc/pwndoc#262]
Can we use the field description in the UI pls above the custom fields rather than the field names which as these are character restricted?
thanks

![image](https://user-images.githubusercontent.com/10500665/153304555-fac6b9f3-6123-404d-839b-f445fd0dda16.png)

**Comment by yeln4ts** [comment]
You can write anything you want in the label field:
![image](https://user-images.githubusercontent.com/4255028/153458284-ce82f443-e077-438a-ba55-f0da6cc5e840.png)
it will be converted to `passwordsecurity` as a template field
