### ISSUE TITLE
Dynamic categories understanding

### ISSUE THREAD

**Issue by pandabottle** [pwndoc/pwndoc#266]
I would like to understand how dynamic category sorting works in pwndoc. Previously, I had made a simple findings list as shown below.
![previous work](https://user-images.githubusercontent.com/79141006/154400512-12cab61a-ab86-4a3f-8244-3dc225a64927.PNG)

My current aim is to make a findings list specific to the category, hence the usage of dynamic category. By following Issue #239 , I attempted to follow the formatting, as shown below.
![category findings](https://user-images.githubusercontent.com/79141006/154400666-81c05c68-18f1-4490-8c84-07ce9d86f378.PNG)

However, while pwndoc generates the report, I get the following error from Word.
![category findings error](https://user-images.githubusercontent.com/79141006/154400702-d9d26db2-3222-442a-afa0-b7e4976010f4.PNG)

Is there perhaps a formatting or an understanding issue for the dynamic category sorting?

**Comment by pandabottle** [comment]
An update: It seemed that the process of updating pwndocs was not complete, therefore the issue has somewhat been fixed after pulling the repository.

However, it still seems that there is not a complete fix for the situation. I had expected that the report will list out the vulnerabilities ranging from high to low as it used to before. However, no vulnerability seems to show up from dynamic categories.

![update](https://user-images.githubusercontent.com/79141006/154471765-18643224-9267-448a-965e-3c2133f836bf.PNG)

I have also noticed the .yml file produced no longer prints out cvssSeverity, which may be the reason why I am facing this issue. Is that the issue at hand or is there something I have missed?

**Comment by yeln4ts** [comment]
Hello,

Please review the changes made in this release: https://github.com/pwndoc/pwndoc/releases/tag/v0.5.0
The CVSS values have changed.

**Comment by pandabottle** [comment]
Thank you for the referral. The issue is now solved.
