### ISSUE TITLE
New findings don't instantly appear in the side pannel

### ISSUE THREAD

**Issue by appstrike** [pwndoc/pwndoc#269]
When adding a new finding within a project, after setting the name and category, I see a success message but the finding is not being added to the left panel. It requires me to manually refresh the page so I can see it appearing there.

**Comment by kazegls** [comment]
I have the same problem with the newest version

**Comment by yeln4ts** [comment]
This is happening if the connection to the server was lost. A classic example would be leaving the web page, putting the computer to sleep and going back to the web page where the websocket connection was interrupted.
Normally you just have to refresh one time, after that it will work again.

**Comment by appstrike** [comment]
I understand your point, but just now I pulled the latest version, made an audit and as quick as possible went and tried to create a finding. Again it didn't show and had to refresh the page. Could you please have a look at it again?

**Comment by yeln4ts** [comment]
I tried building from scratch and did not have this issue.
Could you provide more information like:
- the debug console of your browser
- the debug network of your browser
- logs of the backend: `docker logs -f pwndoc-backend -t`

**Comment by appstrike** [comment]
I understood why that's happening! In the `docker-compose.yml` I have made it so it hosts the application on 443, but the socket.io is somehow hardcoded for 8443, and because there is nothing listening there It fails to connect ...

 
![image](https://user-images.githubusercontent.com/96656932/155425449-8e3fa08f-1786-4278-9d51-cccb479a4106.png)

**Comment by yeln4ts** [comment]
you should also update the environment port in `quasar.conf.js`

**Comment by appstrike** [comment]
Thank you! After changing `./frontend/quasar.conf.js`, line 45 to `API_PORT: 443`, it all started behaving properly.
