### ISSUE TITLE
Feature Request: Styling Code Snippets & Command Output

### ISSUE THREAD

**Issue by appstrike** [pwndoc/pwndoc#275]
Hey,

It will be great if we can somehow mark/style parts of text in a command output or source snippet so they can stand out. Ideally, we can either bold them, change their color, or distinguish them in another way. Whatever is easier to implement, I am sure we can get it to work.

Thanks!

**Comment by relaxedricky** [comment]
Hi,

PwnDoc provides two different [styles](https://pwndoc.github.io/pwndoc/#/docxtemplate?id=styles), one being code and the other being code block. If you don't have these styles in your template, create them, apply your desired style and then when code or code block is used from within PwnDoc, these styles will be used.

**Comment by nitek29** [comment]
Hi,

The problem is that it is not possible to format the text in the code and code block styles in the UI. For example, highlighting the vulnerable header in an HTTP request.
I think it's not a question of style in the template.
