### ISSUE TITLE
If the title of the audit contains a quotation mark, then the name of the word document will not be created correctly. 

### ISSUE THREAD

**Issue by kazegls** [pwndoc/pwndoc#276]
If the title of the audit contains a quotation mark, then the name of the word document will not be created correctly. 

For example when the title auf the audit is named: Webportal "ABC", then the word document file is named: Webportal. It should be named: Webportal "ABC".docx. 

Apparently the quotation mark is interpreted. 

Workaround: Not using special characters

**Comment by relaxedricky** [comment]
Hi,

I've not looked into the code as I think this is a design choice. Windows does not allow `"` in file names, you can however use `'`:

![image](https://user-images.githubusercontent.com/6837440/156760727-53c64d9a-17f0-43a3-8802-fea9bde3c39b.png)

If you have the time feel free to submit some code to enforce the naming convention that will prevent "bad" names from being set.

**Comment by kazegls** [comment]
Thanks, single Quote is working
