### ISSUE TITLE
CVSS Severity None not exported anymore

### ISSUE THREAD

**Issue by Fopje** [pwndoc/pwndoc#279]
I'm running the latest version of pwndoc. The finding with severity None aren't exported anymore when generating a report #83

**Comment by yeln4ts** [comment]
Did you change your template values according to this release: https://github.com/pwndoc/pwndoc/releases/tag/v0.5.0 ?

If yes, did you click all the buttons of the CVSS calculator ? 

Can you provide what you are using in your template to access severity ?

**Comment by Fopje** [comment]
> Did you change your template values according to this release: https://github.com/pwndoc/pwndoc/releases/tag/v0.5.0 ?
> 
> If yes, did you click all the buttons of the CVSS calculator ?
> 
> Can you provide what you are using in your template to access severity ?

I did change them yes. Otherwise the other findings woudn'g generate either. Below an image of the template:

![image](https://user-images.githubusercontent.com/4934752/157668452-31b26d49-3fc7-4adc-a5f7-db0a279045ab.png)

**Comment by yeln4ts** [comment]
Ok so did you click all the buttons of the CVSS calculator ?
If no CVSS is defined then `cvss.baseSeverity == ''`

**Comment by Fopje** [comment]
Before you didn't had to select anything, solved after making a selection.
