### ISSUE TITLE
caption labels don't work when pasting

### ISSUE THREAD

**Issue by AnotherWayIn** [pwndoc/pwndoc#286]
caption labels work when you add a caption manually, but if you just paste a screenshot into the issue description, it names it image.png father than say "Figure 1 - "

**Comment by yeln4ts** [comment]
Images have their own caption. You have to handle them directly in the docx template as mentioned in the documentation: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=html-values-from-text-editors
