### ISSUE TITLE
light mode / dark mode / nmap imports 

### ISSUE THREAD

**Issue by parrotassassin15** [pwndoc/pwndoc#287]
I cannot see the network scans when I import Nmap scans in dark mode I can only see them in light mode

here is the dark mode: 

![Screenshot 2022-03-17 104613](https://user-images.githubusercontent.com/54908247/158830937-b08ee694-8ab6-4400-90e1-c47cf68c602f.png)

here is the light mode: 

![Screenshot 2022-03-17 104821](https://user-images.githubusercontent.com/54908247/158830734-1b5bf192-2b2a-4d95-a30e-9bb3c2aa51e6.png)

**Comment by yeln4ts** [comment]
Yes this PR fixed this issue
