### ISSUE TITLE
Accessing site via IP address

### ISSUE THREAD

**Issue by cyberchinna** [pwndoc/pwndoc#288]
Hello. Is there a way to access the pwndoc site via https://$IP:8443 instead of https://localhost:8443? I would like to access the page from any remote host on the network.  Thanks in advance.

**Comment by relaxedricky** [comment]
You should already be able to access your PwnDoc instance via its IP address.

Can you confirm you have tried this?

**Comment by cyberchinna** [comment]
Hi, sorry for not providing more detail. Yes, I have attempted to access the PwnDoc instance vi its IP. When trying to do so, I get "**Your connection is not private**". After selecting Advanced, I get:

**[Redacted IP] normally uses encryption to protect your information. When Chrome tried to connect to [Redacted IP] this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be [Redacted IP], or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit [Redacted IP] right now because the website sent scrambled credentials that Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.**

Thanks in advance for your help.

**Comment by cyberchinna** [comment]
Any other suggestions?

**Comment by sanvrb** [comment]
You cannot access a website via IP and have a valid SSL certificate. This issue is not related to pwndoc.
https://blog.hubspot.com/website/fix-ssl-certificate-error

**Comment by cyberchinna** [comment]
Greetings, I read a possible work around in issue [CVSS Score Audit sorting #231 ](https://github.com/pwndoc/pwndoc/issues/231) for properly sorting ID numbers. However, I have no idea on how to create the customID to solve this issue. Will someone share how to do so. Thanks in advance.

**Comment by cyberchinna** [comment]
Thanks sanvrb! This did resolve my issue. This issue is now closed.

**Comment by BorysekOndrej** [comment]
> You cannot access a website via IP and have a valid SSL certificate. This issue is not related to pwndoc. 

That's not strictly true, check out for example Cloudflares DNS IP address: https://1.1.1.1/
Getting a cert for IP address that would be generally trusted is not easy, I'm not aware of any cert authority supporting ACME-IP at the moment. Let's Encrypt considered it, but it's [currently not being implemented](https://community.letsencrypt.org/t/certificates-for-ip-addresses/158093).

However if you have have your own certificate authority (for example for internal use inside a company), than it's possible.

**Comment by HuseyinAlpOnat** [comment]
how to make this?

https://$IP:8443 instead of https://localhost:8443/
