### ISSUE TITLE
Sorting Finding IDs

### ISSUE THREAD

**Issue by cyberchinna** [pwndoc/pwndoc#290]
Greetings, I read a possible work around in issue [#231](https://github.com/pwndoc/pwndoc/issues/231) to properly sorting ID numbers. However, I have no idea on how to create the customID to solve this issue. Will someone share how to do so. Thanks in advance.

**Comment by Zeecka** [comment]
Did you had a look at the Custom Fields feature ? (Date > Custom Data > Custom Field).
I think you can add a custom field "customid" for "Audit Findings".
Then according to https://pwndoc.github.io/pwndoc/#/docxtemplate?id=findings you can access to your custom field with `findings[i].customid` and sort using this way: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=sortarraybyfield .
