### ISSUE TITLE
Best way to update the application

### ISSUE THREAD

**Issue by ZigzagSecurity** [pwndoc/pwndoc#291]
Hello, I was wondering what is the best way to update the application once in production. 
I installed it via the release, unzipped the file and launched the docker containers. 

Now if we want to update the application without losing all the data, what's the best way ? 
For now it seems like backing up the database and moving it to the new instance would work great but what if the database is not similar from one version to another ?

Thank you for your time :)

**Comment by Zeecka** [comment]
Hi,

I never experienced breaking change concerning the database for the moment. However, I've seen some concerning the templating (see Changelog https://github.com/pwndoc/pwndoc/blob/master/CHANGELOG.md#update-attention). 
Currently, I have a mirror of the repo, with a production branch. I usually test the master branch on localhost before merging. I pull the production branch when I validated it.
Also, I use the backup functionnaly every week to keep a backup of my vulnerabilities (sadly, audits can't be exported yet) :).
There is also a PR #116 which provide debug step if you experience an issue one day (https://github.com/pwndoc/pwndoc/blob/54aac97c24c12f22f3913123eb7f28bb843e0263/docs/debug.md)

**Comment by yeln4ts** [comment]
Hi,

Here is what I do when I update (I backup the pwndoc folder in case anything goes wrong I can go back to a working instance)
```
cd pwndoc
docker-compose down
cd ..
cp -r pwndoc pwndoc.old
cd pwndoc
git pull
docker-compose build
docker-compose up -d
```

You can use the last tagged version as it should be stable and contains breaking changes information if any.
