### ISSUE TITLE
conditions in template

### ISSUE THREAD

**Issue by AnotherWayIn** [pwndoc/pwndoc#295]
Hey,

is there a way in the template to add conditions?

i'm trying to automate a pass/fail icon into a table based on what words appear in the finding references. e.g: if any finding contains 'xyz' use logo1.png else use logo2.png
![image](https://user-images.githubusercontent.com/10500665/160964901-46dc6f37-7b11-4fa4-b8ad-d21dbe1138c2.png)

many thanks

**Comment by relaxedricky** [comment]
I don't have access to my instance of pwndoc to check, though I can see the doc have [this](https://pwndoc.github.io/pwndoc/#/docxtemplate?id=condition). So I would assume you could do something like the following (result being a custom data you set per vuln):

```
{#result == 'pass'}
logo1.png
{/result == 'pass'}
{#result == 'fail'}
logo2.png
{/result == 'fail'}
```

**Comment by AnotherWayIn** [comment]
> I don't have access to my instance of pwndoc to check, though I can see the doc have [this](https://pwndoc.github.io/pwndoc/#/docxtemplate?id=condition). So I would assume you could do something like the following (result being a custom data you set per vuln):

thanks but i want to check if the reference section contains part of a string like  'if string in references, then do something, else do something else'

**Comment by yeln4ts** [comment]
For complex conditions it would need to be written as a specific filter.
