### ISSUE TITLE
Can't add custom section inside of an Audit

### ISSUE THREAD

**Issue by rudem323** [pwndoc/pwndoc#299]
I've created multiple custom sections, and I can add them to an audit type but I don't get the option to add another custom section once I am in an audit, the documentation shows its possible but I don't see where I can toggle that option. 

Documentation:
![image](https://user-images.githubusercontent.com/47099672/163608023-b32f15a7-1653-4264-a5ac-7033822dea6e.png)

My Audit: 
![Screenshot 2022-04-15 123533](https://user-images.githubusercontent.com/47099672/163608314-cf19049e-6f02-4510-a8be-5163b66cbe14.JPG)

How do I get a + similar to findings, to add more custom sections?

**Comment by relaxedricky** [comment]
Hi,

As far as I am aware, the documentation you are referring to is a little outdated.

The ability to add in a custom section via the "+" is no longer present. You add desired custom sections to the audit type before an audit is created, these can't be added after the fact anymore.

**Comment by rudem323** [comment]
Is there a way to add that feature again?

**Comment by relaxedricky** [comment]
Not that I am aware, you would add the desired sections to the audit types.

**Comment by durantthibault** [comment]
Hello, 

So how is it possible to add custom sections in templates? Is there a new documentation that explains it maybe better?

Thanks by advance

**Comment by AnotherWayIn** [comment]
once you've made the custom field and added it to a custom section you can reference it in the report by its name like so:
![image](https://user-images.githubusercontent.com/10500665/167505990-29cc2350-adff-450c-a46c-3d32b046603c.png)
depending on what type of field it is, the syntax may change a little

**Comment by durantthibault** [comment]
Ok, thank you for your answer

**Comment by DeltaFox0018** [comment]
Hi,
I have the same problem, that after creating the custom section and the custom field I do not have the possibility in the web page to add the custom section
The fact of not being able to add some custom sections is causing me some problems, will the possibility of adding custom section be re-implemented?

Thanks

**Comment by AnotherWayIn** [comment]
have you been into 'audit types' and added the new custom sections to your audit? depending on where you set the custom field's view, you should see it appear

**Comment by DeltaFox0018** [comment]
Hi,
I created a custom section
![image](https://user-images.githubusercontent.com/35847603/168009557-5d35054b-de4f-4e93-9ec9-ea8a304a1d76.png)
And then later I created a custom field in the section just created
![image](https://user-images.githubusercontent.com/35847603/168009627-2f3ce208-9e2a-47d7-b98a-e4be23e1c0a2.png)

The problem is that in the report I don’t have the possibility to add the custom section and this for me is of fundamental importance

Thanks

**Comment by AnotherWayIn** [comment]
what are you adding to the report under the exec summary section? From what you show, the following should work:
```
{#executive_summary.text}
{@text | convertHTML}
{/executive_summary.text}
```

**Comment by relaxedricky** [comment]
Have you also added your section to the desired audit type, example below:

![image](https://user-images.githubusercontent.com/6837440/168038599-4d725fc9-8856-4dc1-97e9-a5bd12b86c59.png)

This is done by going to Data > Custom Data > Audit Types. You will also need to create a new audit once this has been done to have the change reflected.
