### ISSUE TITLE
Demo content template

### ISSUE THREAD

**Issue by braaqwesi** [pwndoc/pwndoc#3]
can you share your demo content template

**Comment by yeln4ts** [comment]
If you mean vulnerabilities, since everyone has its own versions there is no default «starting pack». Maybe I'll add one someday but meanwhile if you ever used Serpico you can import its findings directly in pwndoc

**Comment by tamquanminh** [comment]
@braaqwesi, you can download sample vulnerabilities as link below

https://drive.google.com/file/d/1r4zWMREyyIKqAZ9YjeFYcG25q68pPVNt/view?usp=sharing

**Comment by Pyth3rEx** [comment]
> @braaqwesi, you can download sample vulnerabilities as link below
> 
> https://drive.google.com/file/d/1r4zWMREyyIKqAZ9YjeFYcG25q68pPVNt/view?usp=sharing

Link is sadly down. Anyone have a backup of this?

**Comment by nobox910** [comment]
@Pyth3rEx , I've re-uploaded as link below, you can direct import to your MongoDB

[appsec_sample_vulns.zip](https://github.com/pwndoc/pwndoc/files/13522399/appsec_sample_vulns.zip)

<img width="600" alt="image" src="https://github.com/pwndoc/pwndoc/assets/58721688/840261d1-01fe-48e7-94e2-d8dd0bd18111">

<img width="1053" alt="image" src="https://github.com/pwndoc/pwndoc/assets/58721688/516da09a-9848-4c4e-90b1-6e6c726dcb0f">

**Comment by trnayan** [comment]
@nobox910 Thanks for the vulnerability template sharing, Do you have more category wise templates like WSTG 4.1

**Comment by nobox910** [comment]
@trnayan, you just need to import file [OWASP_WSTG_ASVS_en.json](https://github.com/pwndoc/pwndoc/files/13545526/OWASP_WSTG_ASVS_en.json) via **Import Vulnerabilities** feature.

![image](https://github.com/pwndoc/pwndoc/assets/58721688/4f23a366-73d8-4b44-9f71-91b8d243f55e)

![image](https://github.com/pwndoc/pwndoc/assets/58721688/7714c164-53c3-4fc4-b7aa-18ee8acf3eb2)
