### ISSUE TITLE
Unable to generate reports due to "Server Error"

### ISSUE THREAD

**Issue by gitbork** [pwndoc/pwndoc#301]
A fresh installation of pwndoc in a linux environment (Kali and Ubuntu) is failing to generate reports. All functionality seems to work fine until you go to download a report, when you get a "Server Error" message displayed at the top of the window. We have updated the system it's running on as well as npm in the docker container and nothing has resolved the issues. We have even tried new installs of pwndoc on different machines to no avail. Any assistance would be appreciated.

Monitoring the backend logs shows this:

┌──(kali㉿kali1)-[/opt/pwndoc]
└─$ sudo docker-compose logs -f pwndoc-backend
Attaching to pwndoc-backend
pwndoc-backend     | 
pwndoc-backend     | > pwndoc-backend@0.0.1 start
pwndoc-backend     | > node src/app.js
pwndoc-backend     | 
pwndoc-backend     | Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html
pwndoc-backend     |     at ZipEntries.readEndOfCentral (/app/node_modules/jszip/lib/zipEntries.js:173:23)
pwndoc-backend     |     at ZipEntries.load (/app/node_modules/jszip/lib/zipEntries.js:274:14)
pwndoc-backend     |     at new ZipEntries (/app/node_modules/jszip/lib/zipEntries.js:22:14)
pwndoc-backend     |     at JSZip.module.exports [as load] (/app/node_modules/jszip/lib/load.js:19:18)
pwndoc-backend     |     at new JSZip (/app/node_modules/jszip/lib/index.js:39:14)
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:22:15)
pwndoc-backend     |     at /app/src/routes/audit.js:370:51
pwndoc-backend     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
pwndoc-backend     | Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html
pwndoc-backend     |     at ZipEntries.readEndOfCentral (/app/node_modules/jszip/lib/zipEntries.js:173:23)
pwndoc-backend     |     at ZipEntries.load (/app/node_modules/jszip/lib/zipEntries.js:274:14)
pwndoc-backend     |     at new ZipEntries (/app/node_modules/jszip/lib/zipEntries.js:22:14)
pwndoc-backend     |     at JSZip.module.exports [as load] (/app/node_modules/jszip/lib/load.js:19:18)
pwndoc-backend     |     at new JSZip (/app/node_modules/jszip/lib/index.js:39:14)
pwndoc-backend     |     at Object.generateDoc (/app/src/lib/report-generator.js:22:15)
pwndoc-backend     |     at /app/src/routes/audit.js:370:51
pwndoc-backend     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

We ran the test script too and I have attached the output.

[pwndoc_test_script_output.txt](https://github.com/pwndoc/pwndoc/files/8522532/pwndoc_test_script_output.txt)

**Comment by iansmps** [comment]
Could you solve this problem?
