### ISSUE TITLE
Feature request: Add possibility to generate a API key

### ISSUE THREAD

**Issue by h3dg3h0gg** [pwndoc/pwndoc#306]
Hi ! It would be really nice if users could generate API keys. For the moment, the only way to interact with the API is to authenticate and use the `token` cookie, which resets after about 10 minutes. 

While I understand that it is a great security feature, it makes it very hard for another application to interact with the API without having to manually update the token every 10 minutes, especially if you enable MFA.

Btw, thank you so so much for this great project <3

**Comment by relaxedricky** [comment]
Hi,

I've no idea if this is on the roadmap for @yeln4ts but I think this could help you at the moment.

You could use the refreshtoken endpoint to renew the token, this is how the application does it itself as far as I am aware.

`https://<URL>:8443/api/users/refreshtoken`

This will return json with a new token:

`{"status":"success","datas":{"token":"<redacted>","refreshToken":"<redacted>"}}`

**Comment by yeln4ts** [comment]
Hi,

This is not really on the roadmap as I don't know if it would be useful enough compared to the required amount of work to put it in place.
Generating API keys for 3rd party would need additional work to avoid security flaws and it would need to define exactly what permissions this key would need.
