### ISSUE TITLE
How to Add 2 conditions to one condtion

### ISSUE THREAD

**Issue by rahultalekar** [pwndoc/pwndoc#316]
hello friends, I want to add two conditions to one condition. I am getting errors. 

for example : 
{#findings}
{#category == 'external_finding' && category == 'internal_finding'} {title} {/category == 'external_finding' && category == 'internal_finding'}
{/findings}

it's not working maybe because both conditions contain the category? please help

**Comment by Zeecka** [comment]
I think that you mean `||` instead of `&&` because you can't satisfy both condition with the same variable ;). 
You can have a look at https://docxtemplater.com/docs/angular-parse/#conditions .
Something like this should work :
```
{#findings}
    {#category == 'external_finding' || category == 'internal_finding'}
        {title}
    {/}
{/findings}
```
(you can remove the identation)
