### ISSUE TITLE
Custom Sections

### ISSUE THREAD

**Issue by litsnarf** [pwndoc/pwndoc#32]
When creating a custom section, as explained in the documentation
* https://pwndoc.github.io/pwndoc/#/data?id=custom-sections
* https://pwndoc.github.io/pwndoc/#/docxtemplate?id=custom-sections

I get the following error message.

![image](https://user-images.githubusercontent.com/8859570/96898553-2398e180-1490-11eb-8026-e55b4ae9100b.png)

**Doc Template**

![image](https://user-images.githubusercontent.com/8859570/96898792-71154e80-1490-11eb-99de-0ca8193d8c34.png)

**Back-end**

![image](https://user-images.githubusercontent.com/8859570/96898841-7f636a80-1490-11eb-8bf2-c42565f4627f.png)

**Comment by yeln4ts** [comment]
Thank you, it's an error in the documentation.
The section data is represented like this: <field>: {name: <Name>, text: <HTMLData>}. 
So you have to change {-w:p cleanup} by {-w:p cleanup.text} and {/cleanup} by {/cleanup.text}
You can also use the Name you defined by using {cleanup.name} if you want

**Comment by litsnarf** [comment]
Perfect. That worked just fine.
Thanks
