### ISSUE TITLE
ERROR: Service 'pwndoc-backend' failed to build due to "The command '/bin/sh -c npm install' returned a non-zero code: 137"

### ISSUE THREAD

**Issue by Monst3rSec** [pwndoc/pwndoc#340]
Hi Team,

I have cloned the repo and tried to build the application via docker-compose. But I got the below error and was unable to run the application. 
At 6/11 backend docker build, the npm install command is hanging for more than 30 mins and exited the program 

![image](https://user-images.githubusercontent.com/60444051/181828338-32c24f70-9542-45a6-8024-f4ce350f0aa5.png)

Kindly fix the issue at the earliest. 

Thanks.

**Comment by yeln4ts** [comment]
It could be that you need more space on disk or more RAM. If the 512mb in your hostname corresponds to the RAM then it could be the issue.

**Comment by Monst3rSec** [comment]
The reported issue is fixed based on your suggestion. 

Thanks, Team.
