### ISSUE TITLE
.json serpico import broken

### ISSUE THREAD

**Issue by moscowchill** [pwndoc/pwndoc#343]
In the latest version of pwndoc importing serpico finding export seems broken.
![image](https://user-images.githubusercontent.com/72578879/182393068-4e97645f-45a9-4000-acb5-5860689255f0.png)
Would love to have this working!

**Comment by yeln4ts** [comment]
This is surely because the default serpico vulns don't have language set so it defaults to English with locale 'en'. Either you add language value in each finding from serpico to match your locale or you just add a language with locale 'en' in Pwndoc
