### ISSUE TITLE
Fail at install stage

### ISSUE THREAD

**Issue by waspthebughunter** [pwndoc/pwndoc#361]
Hi ! 

I tried to install on "Ubuntu 22.04.1 LTS", containers are ups, web interface is working but tests are every time while i tried is failing.
Test output is attached.

[pwndoc-verbose.txt](https://github.com/pwndoc/pwndoc/files/9482222/pwndoc-verbose.txt)

**Comment by yeln4ts** [comment]
yes tests are not up to date

**Comment by MaxNad** [comment]
Tests should be working once PR #448 is merged.
