### ISSUE TITLE
How to pageBreakExceptLast in conditionnal loop ?

### ISSUE THREAD

**Issue by Syzik** [pwndoc/pwndoc#369]
Hello, 
This code does not work is there an other way to do this?

```
{#findings}
{#cvssSeverity == 'Critical'}
{title} : {cvssSeverity}
{@$pageBreakExceptLast}
{/cvssSeverity == 'Critical'}
{/findings}
```

Is that a bug or am I doing wrong ?

**Comment by wantafanta** [comment]
Shouldn't it be `cvss.baseSeverity`?

**Comment by Syzik** [comment]
You are right. 
I copy pasted the wrong code. 
The problem remains that I can't get to "pageBreakExceptLast" in conditional loop it work in a norrmal loop.

Doestn't work : 
```
{#findings}
{#cvss.baseSeverity == 'Critical'}
{title} : {cvssSeverity}
{@$pageBreakExceptLast}
{/cvss.baseSeverity == 'Critical'}
{/findings}
```

Work : 
```
{#findings}
{title} 
{@$pageBreakExceptLast}
{/findings}
```

**Comment by wantafanta** [comment]
You still have `cvssSeverity` instead of `cvss.baseSeverity` ?

**Comment by Syzik** [comment]
Sorry I modified the code but it still doesn't have page break between vulnerabilities

**Comment by wantafanta** [comment]
think you just need it on the outside of the condition
```
{#findings}
{#cvss.baseSeverity == ‘Critical’}
{title} : {cvss.baseSeverity}
{/cvss.baseSeverity == ‘Critical’}
{@$pageBreakExceptLast}
{/findings}
```

but you'll get one on every finding that doesn't match Critical too (so a bunch of blank pages). to get around this, assuming you only want to export Criticals, you need to add more, or use a filter (#281)

```
{#findings | where: ‘cvss.baseSeverity == “Critical”’}
{title} : {cvss.baseSeverity}
{@$pageBreakExceptLast}
{/findings | where: ‘cvss.baseSeverity == “Critical”’}
```

**Comment by Syzik** [comment]
Your solution with the PR look good thanks a lot. 
Sorry for the late reply.
