### ISSUE TITLE
It is impossible to add the names of vulnerabilities in Latvian.

### ISSUE THREAD

**Issue by Ejuc** [pwndoc/pwndoc#371]
Ordinary Latvian letters like āčēģīķļņōŗšūž and their respective capital letter versions are impossible to be used in vulnerability titles. There is regexp check that excludes these chars and error is "name and locale value must match /^[A-zÀ-ú0-9 []'()_-]+$/i" 
![image](https://user-images.githubusercontent.com/50964585/193607387-71105f30-6b1f-4a39-b113-87c4b561b4e1.png)

**Comment by Ejuc** [comment]
Has there been any progress in this matter?

**Comment by MaxNad** [comment]
@Ejuc I have opened a pull request that should fix this issue. It will be merged as soon as we can confirm that there are no undesirable side effects

**Comment by MaxNad** [comment]
This issue should now be fixed by commit 74deb01

**Comment by Ejuc** [comment]
Sincere thanks. I will test it as soon as I have a chance.
