### ISSUE TITLE
New collaborators / Dev branch

### ISSUE THREAD

**Issue by Zeecka** [pwndoc/pwndoc#387]
[Edit]
I made a public repo named [pwndoc-ng](https://github.com/pwndoc-ng/pwndoc-ng) to merge pending PR and provide more regular updates 😃.
[/Edit]

Is it possible to add some collaborators to the project and create a dev branch ?
Some PR haven't been reviewed for month, same for issues. Some of them may include security fix.
After talking with some users/devs, we realized that both merged pending PR in our private fork.

Thank you for your work.
Alex

**Comment by Syzik** [comment]
Definitely agreed the idea

**Comment by relaxedricky** [comment]
+1 to this idea.

I understand @yeln4ts is prob busy with life, so having others that can also ensure PR's are added would be great.

**Comment by RobertDoc** [comment]
Has anyone heard from @yeln4ts on this one? Would love to see some of the amazing PRs being merged

**Comment by TheZ3ro** [comment]
If @yeln4ts don't come back I think we would need to make a fork.
What do you guys think?

I see that @Zeecka is interested in developing on this and I'm interested too. Anyone else?
