### ISSUE TITLE
Pwndoc issue

### ISSUE THREAD

**Issue by TemEmmet** [pwndoc/pwndoc#389]
Hi everyone,

I got this error message : 

**The command '/bin/sh -c npm run build' returned a non-zer│
o code: 1                                                │
ERROR: Service 'pwndoc-frontend' failed to build : Build │
failed** 

Someone to help me ?

**Comment by BorysekOndrej** [comment]
Hi, it's hard to guess as your post contains very little information, but it could be the following known issue https://github.com/pwndoc/pwndoc/issues/383. Check the PR that's linked in it.

**Comment by TemEmmet** [comment]
@BorysekOndrej   Thank you, I will check this, so if I understand correctly, the problem would come from the deprecated version of node?

**Comment by ActivateDZA** [comment]
Good day everyone 

I am also getting the same error is there something we need to change?

**Comment by MaxNad** [comment]
Duplicate issue of https://github.com/pwndoc/pwndoc/issues/383
The fix has now been merged
