### ISSUE TITLE
Error Installing on M1 Mac

### ISSUE THREAD

**Issue by tim5700** [pwndoc/pwndoc#390]
Trying to install in Docker on my M1 MacBook Pro w/ Ventura.  Here is the output:

Creating network "pwndoc_backend" with driver "bridge"
Creating volume "pwndoc_mongo-data" with default driver
Pulling mongodb (mongo:4.2.15)...
4.2.15: Pulling from library/mongo
4028d4a2ab03: Pull complete
c50584629502: Pull complete
de80265b7cf7: Pull complete
325293ecfd3d: Pull complete
5c77f99a86fe: Pull complete
2f81425690c9: Pull complete
e54a6b669ef7: Pull complete
7df3df511513: Pull complete
ca2fbfc07112: Pull complete
3445e878771b: Pull complete
Digest: sha256:3dd5aa1b05bf5ac5f985efbd41a39383636ab983c5aa781c0112457c1835b230
Status: Downloaded newer image for mongo:4.2.15
Building pwndoc-backend
[+] Building 41.4s (13/13) FINISHED                                                                                     
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 310B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 63B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                 1.8s
 => [auth] library/node:pull token for registry-1.docker.io                                                        0.0s
 => [1/7] FROM docker.io/library/node:lts-alpine@sha256:ae6cf743c4c290423e163d8a85db7a08b831aace7e2486e857147f78f  5.1s
 => => resolve docker.io/library/node:lts-alpine@sha256:ae6cf743c4c290423e163d8a85db7a08b831aace7e2486e857147f78f  0.0s
 => => sha256:ae6cf743c4c290423e163d8a85db7a08b831aace7e2486e857147f78f0cc34d3 1.43kB / 1.43kB                     0.0s
 => => sha256:32978f0f96a80c94466af439d268a9c1059781988fff38954fd24d86d4da47df 1.16kB / 1.16kB                     0.0s
 => => sha256:2ed2ed37ef035be61915d304162f5a50566e5847e9336b1530736263cec751e3 6.45kB / 6.45kB                     0.0s
 => => sha256:9b18e9b68314027565b90ff6189d65942c0f7986da80df008b8431276885218e 2.71MB / 2.71MB                     0.5s
 => => sha256:46153d5717b7a35997bca1b0ba84e044be96cda6e6ef702b903871ffc336d2e6 46.69MB / 46.69MB                   3.6s
 => => sha256:82d12d33067134171ed6ec6384a2b2910f8653bb0c659f9bfbe06e8eacf947d0 2.41MB / 2.41MB                     0.7s
 => => extracting sha256:9b18e9b68314027565b90ff6189d65942c0f7986da80df008b8431276885218e                          0.1s
 => => sha256:23f929530c00f163590793e53ec24137cf37c627058a2f065662a439055ebe81 447B / 447B                         0.6s
 => => extracting sha256:46153d5717b7a35997bca1b0ba84e044be96cda6e6ef702b903871ffc336d2e6                          1.2s
 => => extracting sha256:82d12d33067134171ed6ec6384a2b2910f8653bb0c659f9bfbe06e8eacf947d0                          0.1s
 => => extracting sha256:23f929530c00f163590793e53ec24137cf37c627058a2f065662a439055ebe81                          0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 1.48MB                                                                                0.1s
 => [2/7] RUN mkdir -p /app                                                                                        0.4s
 => [3/7] WORKDIR /app                                                                                             0.0s
 => [4/7] COPY package*.json ./                                                                                    0.0s
 => [5/7] RUN apk --no-cache add --virtual builds-deps build-base python3 git                                      9.1s
 => [6/7] RUN npm install                                                                                         23.3s
 => [7/7] COPY . .                                                                                                 0.0s 
 => exporting to image                                                                                             1.6s 
 => => exporting layers                                                                                            1.6s 
 => => writing image sha256:4cd3e8d448db458a17c1f69972cdcb41454f6069f09580c3751fb8091aaa2f96                       0.0s 
 => => naming to docker.io/yeln4ts/pwndoc:backend                                                                  0.0s 
                                                                                                                        
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building pwndoc-frontend
[+] Building 73.9s (16/17)                                                                                              
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 435B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 65B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/nginx:stable-alpine                                             1.4s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                 0.3s
 => [auth] library/nginx:pull token for registry-1.docker.io                                                       0.0s
 => [internal] load build context                                                                                  0.2s
 => => transferring context: 2.26MB                                                                                0.1s
 => CACHED [build 1/6] FROM docker.io/library/node:lts-alpine@sha256:ae6cf743c4c290423e163d8a85db7a08b831aace7e24  0.0s
 => [stage-1 1/5] FROM docker.io/library/nginx:stable-alpine@sha256:d24e098389beed466ea300d5473cdda939bf6e91a9387  1.4s
 => => resolve docker.io/library/nginx:stable-alpine@sha256:d24e098389beed466ea300d5473cdda939bf6e91a93873d0fd1dd  0.0s
 => => sha256:d24e098389beed466ea300d5473cdda939bf6e91a93873d0fd1dd18e138c2f13 1.65kB / 1.65kB                     0.0s
 => => sha256:3995ec65c853edc9275f9056f3e4ee26b39bdabc993470d4fae890f18615c2a7 1.57kB / 1.57kB                     0.0s
 => => sha256:64d5c39a424150ad9678f24eb61b0ef66d92c94f8933af7cdbc1b8531c607f2a 8.90kB / 8.90kB                     0.0s
 => => sha256:341b0b8c46a1f5e95c3e0872708a53ac028e44de7aff7d2057ac7084fb414990 956B / 956B                         0.7s
 => => sha256:e78d13e7546ac1d9660b65bc5eacd1aa18008ee9e18e6b19def44acff0890bd0 7.31MB / 7.31MB                     0.8s
 => => sha256:404fe4e73af40566c1e46871ead16732cd5b9e9c1ac7215d17f8754cbe1a6e20 624B / 624B                         0.4s
 => => sha256:d642a3b335668a4846139f99afaf42e938e1964b8d5b09c437ef542bb26bc95c 772B / 772B                         0.7s
 => => sha256:e80328dec171f11fb3aa122deae51efe96f78fab77daf414ecb09635d713c1d2 1.40kB / 1.40kB                     0.8s
 => => extracting sha256:e78d13e7546ac1d9660b65bc5eacd1aa18008ee9e18e6b19def44acff0890bd0                          0.2s
 => => extracting sha256:404fe4e73af40566c1e46871ead16732cd5b9e9c1ac7215d17f8754cbe1a6e20                          0.0s
 => => extracting sha256:341b0b8c46a1f5e95c3e0872708a53ac028e44de7aff7d2057ac7084fb414990                          0.0s
 => => extracting sha256:d642a3b335668a4846139f99afaf42e938e1964b8d5b09c437ef542bb26bc95c                          0.0s
 => => extracting sha256:e80328dec171f11fb3aa122deae51efe96f78fab77daf414ecb09635d713c1d2                          0.0s
 => [build 2/6] WORKDIR /app                                                                                       0.1s
 => [build 3/6] COPY package.json ./                                                                               0.0s
 => [build 4/6] RUN npm install                                                                                   69.5s
 => [stage-1 2/5] COPY .docker/nginx.conf /etc/nginx/conf.d/default.conf                                           0.0s
 => [stage-1 3/5] RUN mkdir -p /etc/nginx/ssl                                                                      0.2s
 => [stage-1 4/5] COPY ssl/server* /etc/nginx/ssl/                                                                 0.0s
 => [build 5/6] COPY . .                                                                                           0.1s
 => ERROR [build 6/6] RUN npm run build                                                                            2.6s 
------                                                                                                                  
 > [build 6/6] RUN npm run build:                                                                                       
#16 0.399                                                                                                               
#16 0.399 > pwndoc-frontend@1.0.0 build                                                                                 
#16 0.399 > quasar build                                                                                                
#16 0.399                                                                                                               
#16 0.535 
#16 0.535  Build mode........ spa
#16 0.535  Pkg quasar........ v1.22.1
#16 0.535  Pkg @quasar/app... v2.4.3
#16 0.535  Debugging......... no
#16 0.535  Publishing........ no
#16 0.535 
#16 0.541  Configured browser support (at least 88.03% of global marketshare):
#16 0.541  · Chrome for Android >= 107
#16 0.541  · Firefox for Android >= 106
#16 0.541  · QQ for Android >= 13.1
#16 0.541  · UC for Android >= 13.4
#16 0.541  · Android >= 107
#16 0.541  · Baidu >= 13.18
#16 0.541  · Bb >= 7
#16 0.541  · Chrome >= 105
#16 0.541  · Edge >= 106
#16 0.541  · Firefox >= 105
#16 0.541  · IE >= 11
#16 0.541  · IE Mobile >= 10
#16 0.541  · iOS >= 15.6
#16 0.541  · Kaios >= 2.5
#16 0.541  · Opera Mini >= all
#16 0.541  · Opera Mobile >= 12.1
#16 0.541  · Opera >= 90
#16 0.541  · Safari >= 15.6
#16 0.541  · Samsung >= 17.0
#16 0.541 
#16 0.709  App · Reading quasar.conf.js
#16 0.713  App · Transpiling JS (Babel active) - includes IE11 support
#16 1.187  App · Extending SPA Webpack config
#16 1.195  App · Cleaned build artifact: "/app/dist/spa"
#16 1.195  App · Generating Webpack entry point
#16 1.198  App · Compiling with Webpack...
#16 1.381  App · Compiling SPA...
#16 1.467   Error: error:0308010C:digital envelope routines::unsupported
#16 1.467   
#16 1.467   - hash:71 new Hash
#16 1.467     node:internal/crypto/hash:71:19
#16 1.467   
#16 1.467   - node:crypto:133 Object.createHash
#16 1.467     node:crypto:133:10
#16 1.467   
#16 1.467   - createHash.js:135 module.exports
#16 1.467     [app]/[webpack]/lib/util/createHash.js:135:53
#16 1.467   
#16 1.467   - NormalModule.js:417 NormalModule._initBuildHash
#16 1.467     [app]/[webpack]/lib/NormalModule.js:417:16
#16 1.467   
#16 1.467   - NormalModule.js:471 handleParseError
#16 1.467     [app]/[webpack]/lib/NormalModule.js:471:10
#16 1.467   
#16 1.467   - NormalModule.js:503 
#16 1.467     [app]/[webpack]/lib/NormalModule.js:503:5
#16 1.467   
#16 1.467   - NormalModule.js:358 
#16 1.467     [app]/[webpack]/lib/NormalModule.js:358:12
#16 1.467   
#16 1.467   - LoaderRunner.js:373 
#16 1.467     [app]/[loader-runner]/lib/LoaderRunner.js:373:3
#16 1.467   
#16 1.467   - LoaderRunner.js:214 iterateNormalLoaders
#16 1.467     [app]/[loader-runner]/lib/LoaderRunner.js:214:10
#16 1.467   
#16 1.467   - LoaderRunner.js:221 iterateNormalLoaders
#16 1.467     [app]/[loader-runner]/lib/LoaderRunner.js:221:10
#16 1.467   
#16 1.467   - LoaderRunner.js:236 
#16 1.467     [app]/[loader-runner]/lib/LoaderRunner.js:236:3
#16 1.467   
#16 1.467   - LoaderRunner.js:130 runSyncOrAsync
#16 1.467     [app]/[loader-runner]/lib/LoaderRunner.js:130:11
#16 1.467   
#16 1.467   - LoaderRunner.js:232 iterateNormalLoaders
#16 1.467     [app]/[loader-runner]/lib/LoaderRunner.js:232:2
#16 1.467   
#16 1.467   - LoaderRunner.js:205 Array.<anonymous>
#16 1.467     [app]/[loader-runner]/lib/LoaderRunner.js:205:4
#16 1.467   
#16 1.467   - CachedInputFileSystem.js:55 Storage.finished
#16 1.467     [app]/[enhanced-resolve]/lib/CachedInputFileSystem.js:55:16
#16 1.467   
#16 1.467   - CachedInputFileSystem.js:91 
#16 1.467     [app]/[enhanced-resolve]/lib/CachedInputFileSystem.js:91:9
#16 1.467   
#16 1.467 
#16 2.520 node:internal/crypto/hash:71
#16 2.520   this[kHandle] = new _Hash(algorithm, xofLen);
#16 2.520                   ^
#16 2.520 
#16 2.520 [  Error: error:0308010C:digital envelope routines::unsupported
#16 2.520   
#16 2.520   - hash:71 new Hash
#16 2.520     node:internal/crypto/hash:71:19
#16 2.520   
#16 2.520   - node:crypto:133 Object.createHash
#16 2.520     node:crypto:133:10
#16 2.520   
#16 2.520   - createHash.js:135 module.exports
#16 2.520     [app]/[webpack]/lib/util/createHash.js:135:53
#16 2.520   
#16 2.520   - NormalModule.js:417 NormalModule._initBuildHash
#16 2.520     [app]/[webpack]/lib/NormalModule.js:417:16
#16 2.520   
#16 2.520   - NormalModule.js:471 handleParseError
#16 2.520     [app]/[webpack]/lib/NormalModule.js:471:10
#16 2.520   
#16 2.520   - NormalModule.js:503 
#16 2.520     [app]/[webpack]/lib/NormalModule.js:503:5
#16 2.520   
#16 2.520   - NormalModule.js:358 
#16 2.520     [app]/[webpack]/lib/NormalModule.js:358:12
#16 2.520   
#16 2.520   - LoaderRunner.js:373 
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:373:3
#16 2.520   
#16 2.520   - LoaderRunner.js:214 iterateNormalLoaders
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:214:10
#16 2.520   
#16 2.520   - LoaderRunner.js:221 iterateNormalLoaders
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:221:10
#16 2.520   
#16 2.520   - LoaderRunner.js:236 
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:236:3
#16 2.520   
#16 2.520   - LoaderRunner.js:111 context.callback
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:111:13
#16 2.520   
#16 2.520   - loader.transform-quasar-imports.js:23 module.exports
#16 2.520     [app]/[@quasar]/app/lib/webpack/loader.transform-quasar-imports.js:23:15
#16 2.520   
#16 2.520   - LoaderRunner.js:119 LOADER_EXECUTION
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:119:14
#16 2.520   
#16 2.520   - LoaderRunner.js:120 runSyncOrAsync
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:120:4
#16 2.520   
#16 2.520   - LoaderRunner.js:232 iterateNormalLoaders
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:232:2
#16 2.520   
#16 2.520   - LoaderRunner.js:221 iterateNormalLoaders
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:221:10
#16 2.520   
#16 2.520   - LoaderRunner.js:236 
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:236:3
#16 2.520   
#16 2.520   - LoaderRunner.js:111 context.callback
#16 2.520     [app]/[loader-runner]/lib/LoaderRunner.js:111:13
#16 2.520   
#16 2.520   - index.js:44 
#16 2.520     [app]/[babel-loader]/lib/index.js:44:71
#16 2.520   
#16 2.520 ] {
#16 2.520   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#16 2.520   library: 'digital envelope routines',
#16 2.520   reason: 'unsupported',
#16 2.520   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#16 2.520 }
#16 2.520 
#16 2.520 Node.js v18.12.1
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
ERROR: Service 'pwndoc-frontend' failed to build : Build failed

**Comment by BorysekOndrej** [comment]
Hi, this looks like this known issues https://github.com/pwndoc/pwndoc/issues/383. Check the PR that's linked from it.

**Comment by MaxNad** [comment]
Duplicate issue of #383
The fix has now been merged
