### ISSUE TITLE
Help in import

### ISSUE THREAD

**Issue by meetgyn** [pwndoc/pwndoc#4]
Sorry for my ignorance. I am trying to import the vulnerability package from OWASP, PTEs, and OSCP. But I can't port on the system. Would you have a model to make available?
Another problem would be Temples, how do I configure it?

**Comment by yeln4ts** [comment]
For the vulnerability import you can see the Vulnerability management section in the README: https://github.com/pwndoc/pwndoc#vulnerabilities-management
It shows an examle of the format it should have.

For the Templates you can see the Templates section in the README: https://github.com/pwndoc/pwndoc#templating
