### ISSUE TITLE
The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by PinkDev1** [pwndoc/pwndoc#40]
# Replicate issue
Fresh install:
```
git clone https://github.com/pwndoc/pwndoc
cd pwndoc
sudo docker-compose up -d --build
sudo docker-compose start
```

Browse `http://localhost:8443/`
OR
`curl http://localhost:8443/`
 
# Error
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx/1.18.0
```

# Environment
Browser: Firefox 82.0.1 (64-bit)
OS: 5.8.0-kali3-amd64
```
docker-compose --version
docker-compose version 1.25.0, build unknown

docker --version
Docker version 19.03.13, build 4484c46
```

# Logs
```
sudo docker-compose logs -f pwndoc-backend
Attaching to pwndoc-backend
pwndoc-backend     | 
pwndoc-backend     | > pwndoc-backend@0.0.1 start /app
pwndoc-backend     | > node src/app.js
pwndoc-backend     | 
^CERROR: Aborting.
```

**Comment by yeln4ts** [comment]
The application must be accessed in HTTPS as indicated in the [documentation](https://pwndoc.github.io/pwndoc/#/installation?id=production):
![image](https://user-images.githubusercontent.com/4255028/97475992-4c9ff300-1924-11eb-8e71-000b0edc38f7.png)

**Comment by PinkDev1** [comment]
My bad :p
Now I'm getting another error, but I'll describe it in another issue.
However, this should still be adressed: Either implement a redirect, or implement [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) (Recommended: Both)

Reopen

**Comment by sujin-lifology** [comment]
I'm getting also the same error when runnig tooljet in docker is there any solution?

**Comment by ItsIgnacioPortal** [comment]
> I'm getting also the same error when runnig tooljet in docker is there any solution?

You have to use an **https** URL.
