### ISSUE TITLE
No Network Scan and Results at Audit

### ISSUE THREAD

**Issue by Bagiadrums** [pwndoc/pwndoc#420]
I have set up Pwndoc with docker on my Kali VM.
When I go to an audit, I don't see the menu item Network Scan and Results.
When I reload the page it is there briefly, but disappears again.
Did I use the tool wrong or do I have a broken installation?
I use npm 8.11.0 and changed like in issue #383 
any help?
<img width="298" alt="image" src="https://user-images.githubusercontent.com/62818376/207667853-6bef1f00-3820-4887-b9b0-247a19a98a00.png">

**Comment by Zeecka** [comment]
It work fine on my side, including for German language:
![image](https://user-images.githubusercontent.com/24873615/207717719-0c828873-785e-417d-b46a-0fa59ab0cda4.png).
Do you have javascript or network error (F12) ? Did you tried on an other browser ? Did you clear your docker cache before building ?

**Comment by Bagiadrums** [comment]
So after a long debugger, looking at logs, reinstalling and co. I have the solution.
I just checked the checkbox "Network Scan" and "Results" when creating the audit types. That was the Problem :)
