### ISSUE TITLE
docker compose issue

### ISSUE THREAD

**Issue by EIT-AUS** [pwndoc/pwndoc#431]
issue 1 
Node.js v18.13.0
ERROR: Service 'pwndoc-frontend' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1

issue 2 
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

**Comment by thecowmilk** [comment]
I have the same problem here!

**Comment by kazegls** [comment]
Here is the fix: https://github.com/pwndoc/pwndoc/pull/384

**Comment by thecowmilk** [comment]
i wonder why you don't make it by default since it seems its a crucial step to do

**Comment by relaxedricky** [comment]
This project currently getting any updates, a new fork by some of the users has been made [here](https://github.com/pwndoc-ng/pwndoc-ng). I would recommend checking it out

**Comment by thecowmilk** [comment]
Well that is helping! Thanks @relaxedricky

**Comment by MaxNad** [comment]
Duplicate of #383.
The fix has been merged.
