### ISSUE TITLE
[Question] Install on Synology NAS?

### ISSUE THREAD

**Issue by rdtm443** [pwndoc/pwndoc#433]
Hello folks

During my search for a pentest reporting tool, I stumbled over PwnDoc. Would love to install it on my Synology NAS, but due to lack of deeper knowledge concerning docker, I am not able to.

Did anyone achieve to install it on a Syno NAS? If yes, how?

Got other dockers running on it, installed either via docker command or docker-compose through portainer (stack). But with this, it seems a bit different.

Thanks a lot!

**Comment by MaxNad** [comment]
This issue was handled in another fork.
For reference, deployment can be done using docker-compose with
```
git clone git@github.com:pwndoc-ng/pwndoc-ng.git
cd pwndoc-ng
docker compose up -d
```
