### ISSUE TITLE
[Question] Where can I find API documentation?

### ISSUE THREAD

**Issue by rafchillons** [pwndoc/pwndoc#434]
There is a link to /api in the instructions for setting up a web application, but I did not find documentation for it. Does anyone have a list of methods in swagger format?

**Comment by MaxNad** [comment]
As far as I know, there is no formal documentation for the backend APIs. However, you can generate a swagger file from the routes by installing the "swagger-autogen" (`npm i swagger-autogen`) dependency and running the following script in the project root.
```
const fs = require('fs');
const swaggerAutogen = require('swagger-autogen')();

const routesFolder = './backend/src/routes/';

const outputFile = './swagger_output.json';
const endpointsFiles = [];

var files = fs.readdirSync(routesFolder);
files.forEach(file => {
    let fileStat = fs.statSync(routesFolder + '/' + file).isDirectory();
    if(!fileStat) {
        endpointsFiles.push(routesFolder + '/' + file);
    }
});

swaggerAutogen(outputFile, endpointsFiles);
```

This could be integrated in the build process at some point by adding it in the package.json

**Comment by MaxNad** [comment]
API documentation is now available at [https://pwndoc.github.io/pwndoc/api/](https://pwndoc.github.io/pwndoc/api/)
