### ISSUE TITLE
Default data to import

### ISSUE THREAD

**Issue by wing0ver** [pwndoc/pwndoc#45]
Hi,

I see we can import vulnerabilities from json or yaml file.
Is there any place we can find such a file, in order to import common vulnerabilities to start with ? 

Thanks in advance

**Comment by yeln4ts** [comment]
You can see #3 someone created some basic vulnerabilities.
You can also use Serpico default vulnerabilities as the application also handle Serpico format: https://raw.githubusercontent.com/SerpicoProject/Serpico/master/templates/template_findings.json

**Comment by lucaDalSeno** [comment]
Hi,

thanks for that template. I even created and export some vulnerabilities from pwndoc. 
Then I tried to import those vulnerabilities on a new installation, everything got imported with no error, but under "Vulnerabilities" tab there's nothing. And if I try to import again the same vulnerabilities it says that they are already imported.
Did I miss something?

Thanks in advance

**Comment by wing0ver** [comment]
@lucaDalSeno , I managed to import the file on a new docker installation. Maybe you can check if english language is correctly set.

**Comment by yeln4ts** [comment]
It's because the language is not set correctly. The language of the imported vulnerabilities must match the locale language in the data section.

**Comment by litsnarf** [comment]
> 
> 
> Hi,
> 
> thanks for that template. I even created and exported some vulnerabilities from pwndoc.
> Then I tried to import those vulnerabilities on a new installation, everything got imported with no error, but under "Vulnerabilities" tab there's nothing. And if I try to import again the same vulnerabilities it says that they are already imported.
> Did I miss something?
> 
> Thanks in advance

I think I had a similar issue. When you export the vulns from serpico, then open the file and replace all `language: en` with `language: EN` (capitalized) or make sure that the it matches whatever you have in your environment.
