### ISSUE TITLE
Scope table not listing items

### ISSUE THREAD

**Issue by Zeecka** [pwndoc/pwndoc#451]
**Describe the bug**
When reloading audit, scope items shows as `[Object object]`.

**To Reproduce**
1. Create an audit
2. Add data in "scope" field
3. Reload page

**Expected behavior**
Items filled in "scope" field should display their name instead of `[Object object]`.

**Screenshots**
![image](https://user-images.githubusercontent.com/24873615/228021956-b2192172-cad8-412c-8ed7-bd602719cbfb.png)

**Environment (please complete the following information):**
 - Tested on Firefox / Chrome

**Additional context**
Scope name display well in network view.

**Comment by rlvilla** [comment]
I'm getting the same bug. Also, when I try to save the edits in Audit/General, I get the following error:

![imagen](https://user-images.githubusercontent.com/16118866/228046961-2e0dd784-5663-4d96-b7be-6764b78851a5.png)
