### ISSUE TITLE
custom field parses  [object Object]	

### ISSUE THREAD

**Issue by shorefall** [pwndoc/pwndoc#454]
Hi!

I added a custom field for the section vulnerability with the "editor" component.
it shows for testing now like this:
![image](https://user-images.githubusercontent.com/72578879/228513853-90f9df22-747f-489e-8b9f-c0e579270a9b.png)

When I try to to use {impact_samenvatting} in the report template it parses the following into the field: [object Object] instead of the data I included in the custom section.

![image](https://user-images.githubusercontent.com/72578879/228514416-c7a3d838-7cb2-4df5-a051-ed3be2594cf9.png)

What am I doing wrong here?

**Comment by rlvilla** [comment]
I believe this is related to #451. Looks like it is a new requirement for Mongoose which has been recently updated. It has already been fixed in a pull request (#452)

**Comment by yeln4ts** [comment]
HTML data cannot be used directly as a tag in the template. You should follow the documentation: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=html-values-from-text-editors
