### ISSUE TITLE
Some question about document in MongoDB

### ISSUE THREAD

**Issue by edwardtyson** [pwndoc/pwndoc#458]
This is not a bug, but I would appreciate it if you could help me with a question I have.

- 1 document in audits
`{"_id":{"$oid":"6436e70ba7e37f001140da19"},"collaborators":[],"reviewers":[],"state":"EDIT","approvals":[],"name":"Test","language":"en","auditType":"Fully Penetration Testing","type":"wa","creator":{"$oid":"63ad6088df6e5100117919ea"},"sections":[],"customFields":[{"customField":{"displaySub":"","size":12,"offset":0,"required":false,"description":"","_id":"63915bdc8504160011a46261","fieldType":"text","label":"Except","display":"general","options":[]},"text":""},{"customField":{"displaySub":"","size":12,"offset":0,"required":false,"description":"","_id":"636362e2decd33001184296a","fieldType":"input","label":"Version","display":"general","options":[]},"text":""},{"customField":{"displaySub":"","size":12,"offset":0,"required":false,"description":"","_id":"63636432decd33001184296e","fieldType":"text","label":"Recommend","display":"general","options":[]},"text":""}],"template":{"$oid":"63ad005e2bea640011e6a963"},"sortFindings":[{"category":"Web Pentest","sortValue":"cvssScore","sortOrder":"desc","sortAuto":true}],"scope":[],"findings":[],"createdAt":{"$date":"2023-04-12T17:14:51.049Z"},"updatedAt":{"$date":"2023-04-12T17:14:54.726Z"},"__v":0}`

What is the meaning of the __v key in the document, and if I change it to any other number such as "__v":55, what will happen? Will it affect my audits?

-----------------------------------------------------------------------------------------------------------------------

- 1 document in images
`{"_id":{"$oid":"6361df2e08a0fd0011a2374a"},"value":"data:image/png;base64,iVBORw0KGgoA...","name":"SQLI.png","auditId":{"$oid":"6361dc6108a0fd0011a2370f"},"createdAt":{"$date":"2022-11-02T03:08:30.689Z"},"updatedAt":{"$date":"2022-11-02T03:08:30.689Z"},"__v":0}`

Are the "createdAt" and "updatedAt" keys in a document important? If I add another document without these two keys and use it in audits, what will happen?

Thank you for your help!

**Comment by MaxNad** [comment]
The `__v` attribute is handled automatically by mongoose to store the internal revision number of the document (see [versionKey](https://mongoosejs.com/docs/guide.html#versionKey)).

Changing this on certain objects would have almost no impact whereas changing it on objects in an array may very well break things.

The `createdAt` and `updatedAt` fields are also automatically handled by mongoose ([https://mongoosejs.com/docs/timestamps.html](https://mongoosejs.com/docs/timestamps.html)).

Adding object without it may break the flow of certain operations if PwnDoc relies on it (or is changed to rely on it in the future).

In general, tampering with the data format directly in the database is not the safest thing. If you are looking to to do certain things, I would advise creating a ticket requesting the feature for direct integration in the project instead.

**Comment by edwardtyson** [comment]
Thank you for your helpful explanation.
