### ISSUE TITLE
Template generation - Sorting via CVSS score

### ISSUE THREAD

**Issue by litsnarf** [pwndoc/pwndoc#463]
Since the last update I can't find a way to sort the issues/findings based on the CVSS score. I've tried with a lot of different sorting options but none seems to work. What was working before was the following:

To sort via CVSS score and then get only the Critical ones 
```
{#findings | sort: 'cvss.baseMetricScore': -1}{#cvss.baseSeverity == 'Critical'}
{title}
{/cvss.baseSeverity == 'Critical'}
{/}
```

The followings are the combinations that I've tried, but I was always getting `Scope parser execution failed` when trying to download the report:

```
{#findings | sort 'cvss.baseMetricScore'}{#cvss.baseSeverity == 'Critical'}...

{#findings | sort: 'cvss.baseMetricScore'}{#cvss.baseSeverity == 'Critical'}...

{#findings | sort cvss.baseMetricScore}{#cvss.baseSeverity == 'Critical'}...

{#findings | sortArrayByField: 'cvss.baseMetricScore'}{#cvss.baseSeverity == 'Critical'}...

{#findings | sortFindings: 'cvss.baseMetricScore'}{#cvss.baseSeverity == 'Critical'}...
```

I cant' seem to find a combination that works (the ones in the documentation seem to be outdated?)

Thank you.

**Comment by yeln4ts** [comment]
Unrelated to the issue but looking at your example I think you should use `sortArrayByField` which takes the order parameter that you are using:
```
{#findings | sortArrayByField: 'cvss.baseMetricScore': -1}
{#cvss.baseSeverity == 'Critical'}
{title}
{/cvss.baseSeverity == 'Critical'}
{/}
```
