### ISSUE TITLE
Icon for adding Custom Sections does not appear

### ISSUE THREAD

**Issue by brunomcuesta** [pwndoc/pwndoc#467]
Hello!
I created my custom sections, but the "add icon" does not appear in the sidebar. They are appearing separately.

These are my Custom Sections.

![image](https://github.com/pwndoc/pwndoc/assets/816237/48802d3d-1624-4dbd-a8e4-23ffb1b3e1fd)

And in this example I took from the Internet, an icon for adding is shown, just like the "Findings" option.

![image](https://github.com/pwndoc/pwndoc/assets/816237/f0545665-ef48-4ee5-85c2-2eab280476bf)

How to put this Add Sections icon?
Thanks!

**Comment by yeln4ts** [comment]
It was not updated in the documentation but the Sections are now defined in the Audit Type configuration:
![image](https://github.com/pwndoc/pwndoc/assets/4255028/a210a4c8-6ffb-4b8b-b2cb-5d528b832079)

**Comment by brunomcuesta** [comment]
Hello!
I had already added the sections in that option, but the add sections icon does not appear in the sidebar.

![image](https://github.com/pwndoc/pwndoc/assets/816237/3b7f2fc6-50d0-4315-873d-aa191d6fe164)

Is there any configuration left to do?
Thanks!

**Comment by yeln4ts** [comment]
The add sections icon was removed a while ago
