### ISSUE TITLE
Enhancement: Custom Fields for findings/vulns

### ISSUE THREAD

**Issue by KoEnix** [pwndoc/pwndoc#47]
Hi,
first of, I really like your project, its really nice and easy to work with.
While developing our report template, we thought it would be nice
and also really helpful, to be able to add custom fields to findings, or
vulnerabilitys in general as well, if we want to include even more
information to a hole.

Thanks in advanc.e

**Comment by yeln4ts** [comment]
Thank you :smiley: 

It's already possible to have custom fields by creating a custom category. Each category can contain multiple additional fields (input or text). You then have to add vulnerabilities to this custom category and it will contain all your custom fields that will be accessible in your docx template like this: 

![image](https://user-images.githubusercontent.com/4255028/98280448-69ae7480-1f69-11eb-9d4e-3bc04a99740f.png)

I'm thinking of a way to also have global custom fields not related to vulnerabilities that will be accessible from the finding edit section.

**Comment by KoEnix** [comment]
Ok, nice, found it. Thanks a lot. Just another question: Is there a way to display these custom vuln fields only when present, e.g. like an if-clause?
And when we are talking about categories, is there a way when templating, to sort the findings based on the categorie?
Or even split and sort them findings based on the categorie?

**Comment by yeln4ts** [comment]
Yes all that is possible with the docx templating: https://pwndoc.github.io/pwndoc/#/docxtemplate
For example for sorting by category you could do the same thing as the condition example in the documentation
`{#findings}
{#category == 'example'}
{title}
{/category == 'example'}
{/findings}`
`{#findings}
{#category == 'example2'}
{title}
{/category == 'example2'}
{/findings}`
