### ISSUE TITLE
Numbered Lists Formatting

### ISSUE THREAD

**Issue by lukewegryn** [pwndoc/pwndoc#470]
**Describe the bug**
When using numbered lists in any text field, if the list is broken up by some other content (text not in the list, a code block, an image, etc) then the list is continued, the formatting will be wrong when the user navigates away and then navigates back.

**To Reproduce**
1. Go to any text box with numbered lists available as a formatting option.
2. Enter a couple of numbered items.

```
1. Here is the first item
2. Here is the second item
```

3. Insert some text that is not numbered, then continue the numbering.

```
1. Here is the first item
2. Here is the second item
Here is some normal text that is not in the numbered list
3. Now, the numbers continue.
```
4. Save the text.
5. Navigate away, and then navigate back
4. See the issue, specifically that the text now has HTML and bullets in it.

```
1. Here is the first item

2. Here is the second item

Here is some normal text that is not in the numbered list

<ol start="3">

• Now, the numbers continue.
```

**Expected behavior**
Numbered lists will save the same way they appear to be formatted when creating them.

**Screenshots**
![Screenshot 2023-06-20 at 8 14 28 AM](https://github.com/pwndoc/pwndoc/assets/7506866/4232a8cd-e6c2-4157-b092-6ee6b59dbd2e)
![Screenshot 2023-06-20 at 8 14 39 AM](https://github.com/pwndoc/pwndoc/assets/7506866/9a087228-3114-4530-96f5-bb0f540f35ee)

**Environment (please complete the following information):**
 - Chrome (Brave)

**Comment by yeln4ts** [comment]
I can't reproduce your issue, if I put text between numbered list, the numbering doesn't continue but restart:
![image](https://github.com/pwndoc/pwndoc/assets/4255028/c238c71b-722f-4ed4-b9a3-6f23bb31fa60)

Can you provide exactly what you type or click to reproduce ?

**Comment by lukewegryn** [comment]
Thanks @yeln4ts!
