### ISSUE TITLE
Generator error: listings from text fields inserted wrong

### ISSUE THREAD

**Issue by KoEnix** [pwndoc/pwndoc#48]
Hi,
while inspecting a generated test-report, i noticed that the listings in text fields aren't inserted properly. Instead of generating a unnumberd list, it generates a numberd list, starting at 0, then 1, and so on.

Starting Situation:
  Regular unordert list of items in a text field

Expected Result:
  regular unordert list with bullets in word

Results got:
  Numbered List, starting at "0"

**Comment by yeln4ts** [comment]
I invite you to look at this section of the documentation: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=styles
The numbering is correctly set in the default template of this repo but if you want to start from another document you have to check the numbering.xml file like explained in the documentation.
