### ISSUE TITLE
Error with Deleted Vulnerabilities

### ISSUE THREAD

**Issue by daniel2005d** [pwndoc/pwndoc#481]
Vulnerabilities are created within an existing audit, but these are deleted because they may or may not be duplicated, at the time of generating the report, the vulnerabilities that had been deleted appear within the document.

Steps to reproduce

Within an existing audit, create several vulnerabilities and eliminate some of them (test creating the same vulnerability several times).
In the report, have a section where you list the vulnerabilities, something like:

{#findings}{#cvss.baseSeverity   == 'Critical'}   {cvss.baseSeverity} | {title} | Activa | {/cvss.baseSeverity == 'Critical'}{/findings}
{#findings}{#cvss.baseSeverity   == 'High'}   {cvss.baseSeverity} | {title} | Activa | {/cvss.baseSeverity == 'High'}{/findings}
{#findings}{#cvss.baseSeverity   == 'Medium'}   {cvss.baseSeverity} | {title} | Activa | {/cvss.baseSeverity == 'Medium'}{/findings}
{#findings}{#cvss.baseSeverity   == 'Low'}   {cvss.baseSeverity} | {title} | Activa | {/cvss.baseSeverity == 'Low'}{/findings}

And download the report, those eliminated vulnerabilities appear.

**Comment by yeln4ts** [comment]
I can't reproduce your issue. Are you sure you deleted them effectively ? (try refreshing the page to be sure)
Can you provide screenshots of the audit page and the word section with the findings ?
