### ISSUE TITLE
Custom section not working

### ISSUE THREAD

**Issue by daniel2005d** [pwndoc/pwndoc#486]
I create a new section to use:
![image](https://github.com/pwndoc/pwndoc/assets/9272841/d8a2a657-85ea-4369-b0fa-e162986a24e1)

After creating the custom section mentioned above, proceed to create a new custom field within that section

![image](https://github.com/pwndoc/pwndoc/assets/9272841/ed399ec5-08fd-47e8-9984-cd3a333c98f2)

After creating a new audit, the custom section does not appear
![image](https://github.com/pwndoc/pwndoc/assets/9272841/b4fa8256-1ed1-4656-bd02-936f7192439a)

![image](https://github.com/pwndoc/pwndoc/assets/9272841/70611907-4489-4307-bb53-11eaff0cbeab)

What's the problem?

**Comment by yeln4ts** [comment]
You need to add the sections in your Audit type configuration

**Comment by daniel2005d** [comment]
Thanks a lot. That's working 4 me.
