### ISSUE TITLE
Multiple screenshot upload for proof not showing

### ISSUE THREAD

**Issue by IanPuraSec** [pwndoc/pwndoc#489]
I just installed a fresh copy from github on a clean vm. 

In the demo gif (https://raw.githubusercontent.com/pwndoc/pwndoc/master/demos/audit_finding_demo.gif) you can see under proof that a folder can be uploaded with all screenshots. 

This doesn't become visible for me in my installation.

**Comment by wantafanta** [comment]
its an old gif, that doesn't exist anymore. you just paste from the clipboard or use the insert image button.

**Comment by IanPuraSec** [comment]
> its an old gif, that doesn't exist anymore. you just paste from the clipboard or use the insert image button.

Oh never seen it. I've been using PwnDoc since 2022. Actually was happy to see this was, I thought, introduced.
