### ISSUE TITLE
Something went wrong contacting backend

### ISSUE THREAD

**Issue by xiaoliangli1128** [pwndoc/pwndoc#49]
hi !
I build it with docker-compose, When I first visite  localhost:8443,
it display  : Something went wrong contacting backend
What should I do?

**Comment by yeln4ts** [comment]
I guess you are using Firefox: https://pwndoc.github.io/pwndoc/#/installation?id=production

**Comment by chunduru5** [comment]
When I open pwndoc I am getting the message
something went wrong contacting backend
How can I rectify it?? Can you guys please tell me?
