### ISSUE TITLE
CVSS object attributes are always undefined

### ISSUE THREAD

**Issue by lith0phagous** [pwndoc/pwndoc#492]
When exporting an audit containing CVSSv3.1, the values inside the document are always undefined

my mongo:
![mongo](https://github.com/pwndoc/pwndoc/assets/95074355/e86b7b1d-fdf2-42a9-82d7-0ceb7e1c79ef)

my docx template:
![template](https://github.com/pwndoc/pwndoc/assets/95074355/f54fd7ee-816b-4a43-983e-c6cddc6bd1c8)

the generated document content:
![outputdoc](https://github.com/pwndoc/pwndoc/assets/95074355/9e484d50-f545-4c82-9eaa-4714cbb264b6)

**Comment by wantafanta** [comment]
not a bug…. 

https://github.com/pwndoc/pwndoc/issues/254#issuecomment-1025761822

and you just need {value} without .title

**Comment by lith0phagous** [comment]
> not a bug….
> 
> [#254 (comment)](https://github.com/pwndoc/pwndoc/issues/254#issuecomment-1025761822)
> 
> and you just need {value} without .title

My bad, thanks
