### ISSUE TITLE
Fields with default values do not exist within the database

### ISSUE THREAD

**Issue by RaduNico** [pwndoc/pwndoc#503]
Attempting to reference the **affected** field in a template if the affected resource has the default empty value results in an error when generating a report. (see picture) The field "scope" does not appear to be created in the database for newly created findings. The reason I am attempting to access the field in the template is to add a TODO in the report if the field does not have a value set. I am using the following text in the report template:

`{#affected == ''}TODO{/affected == ''}`

The same behavior is present in the case of custom text (Editor) fields with the default value.

**To Reproduce**
1. Create new finding
2. Use a template containing `{#affected == ''}TODO{/affected == ''}`
3. Attempt to create a report

**Expected behavior**
Create a report and correctly evaluate the affected resources / custom text field as being empty

![image](https://github.com/pwndoc/pwndoc/assets/40314810/ed6a2865-a3fe-4b17-be87-83007542d163)

**Comment by yeln4ts** [comment]
Is the `{affected}` tag inside a `{findings}` tag ?

**Comment by RaduNico** [comment]
In my attempt to create a very simple way to reproduce the issue I forgot to add the `{affected}` tag inside a `{findings}` tag. Using the structure `{#affected == ''}TODO{/affected == ''}` is correctly evaluated by pwndoc. The test template I created was not correctly formatted and I red herringed myself.

The way I am trying to use the affected tag is like this:

```
{#findings}
{#affected == ''}TODO EMPTY AFFECTED{/affected == ''}{@affected | convertHTML: ‘AffectedResources’}
{/findings}
```

And this does result in an the above mentioned error. The expected behavior would be to put the placeholder text 'TODO EMPTY AFFECTED' if the affected textbox is empty or to use the content if it's not empty.

**Comment by yeln4ts** [comment]
{@} tags need to be on its own line. Your example will work like this:
```
{#findings}
{#affected == ''}
TODO EMPTY AFFECTED
{/affected == ''}
{@affected | convertHTML: 'AffectedResources'}
{/findings}
```

**Comment by RaduNico** [comment]
Doing it this way will always introduce a newline above the affected data because the newline after `{/affected == ''}`. Is there any way around this or just a limitation of pwndoc ?

**Comment by yeln4ts** [comment]
PwnDoc is handling the data but the templating of word documents is done using the docxtemplater module https://docxtemplater.com/docs/tag-types/ 

What commit do you use ? Because docxtemplater `paragraphLoop` option should handle this case: https://github.com/open-xml-templating/docxtemplater/blob/master/CHANGELOG.md#322

**Comment by RaduNico** [comment]
I've done more testing and it seems that it was classic PEBCAK. There was a white space character forgotten in the template, and it was treating it as a non-empty line, thus keeping the newline. Using it as described works as expected. Thank you for taking the time to respond.
