### ISSUE TITLE
Findings won't populate unless page is refreshed

### ISSUE THREAD

**Issue by HeadGapped** [pwndoc/pwndoc#505]
When adding Findings to an audit they won't show up under the Findings heading unless I refresh the page.

After refreshing the page, they are all there. This also occurs when I delete findings. In this instance they stay on the page until refreshed. 

I have noticed from the monitoring the frontend logs when I add a finding in an audit Pwndoc will do a single POST request but not the 4 following GET requests until the page is refreshed.

Thanks,

**Comment by yeln4ts** [comment]
Do you use specific networking configuration like proxy or else ? Because when adding findings a websocket handles the refresh on the sidebar so it's normal to not see the GET requests.

**Comment by Xitro01** [comment]
Same issue, only thing is that I duplicated the whole pwndoc stack and used different container names and one-upped the port numbers. Had to do some changes to the config files, but it works. Only thing is that the Findings do not refresh automatically.
Would be great to know how to solve this.
