### ISSUE TITLE
Retest

### ISSUE THREAD

**Issue by fabianalvarez317** [pwndoc/pwndoc#520]
When will they work on adding retest?

**Comment by CyberzSentry** [comment]
They already do. You have to create a Retest Audit Type in the Custom Data section and the Retest button in audit will work.

**Comment by akdir** [comment]
I have added the Retest Audit type in the Custom data and the Retest button works, but what are the DOCX template object names for the retest Description and retest Status? If I add {#retestDescription} and {#retestStatus} to my template file, I get the error when generating a report that it `Cannot read properties of undefined (reading 'substring')`.

Can anyone help me?

**Comment by yeln4ts** [comment]
I need to rework the documentation but I don't have the time for now.
Here is how to use retest in the template:
```
{#findings}
{#retestStatus == 'ok'}fixed{/}
{#retestStatus == 'ko'}not fixed{/}
{#retestStatus == 'partial'}partially fixed{/}
{#retestStatus == 'unknown'}can't verify if it is fixed{/}

{#retestDescription}
{@text | convertHTML}
                          {#images}
                          {%image}
                          Image 1 – {caption}
                          {/images}
{/retestDescription}
{^retestDescription}
No proof needed.
{/retestDescription}
{/findings}
```
