### ISSUE TITLE
Set password adding new colaborator is not working

### ISSUE THREAD

**Issue by codigoartesano** [pwndoc/pwndoc#521]
**Describe the bug**
Is not possible add a new collaborator, because is not possible add a password

**To Reproduce**
1. Go to 'Data'
2. Click on 'Collaborators'
3. Click on 'Add new collaborator'
4. Complete the fields
5. Try to add new password... is not working
6. Click on create

**Expected behavior**
 If I use a complex password or use minimal requirements the filed is blank always

**Screenshots**
<img width="589" alt="image" src="https://github.com/pwndoc/pwndoc/assets/125426068/29c3f87a-4e54-4d61-b6c6-a41e4ec5555e">

**Environment (please complete the following information):**
 - Browser used; Chrome and Brave

**Comment by codigoartesano** [comment]
Update, if the password is good.. but other field is not filled, the alert is showed in the password filed :S

**Comment by yeln4ts** [comment]
Thank you I'll investigate the issue. It seems to be because of the rules validation not correctly syncing the value.
