### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by bigmrw** [pwndoc/pwndoc#53]
I have been testing PwnDoc out over the past week and really see the value in using it.  I am wondering if anyone could provide me with a data set that would be useful for penetration testing?  I am looking for a generic list of vulnerability types and categories that I can import.

**Comment by yeln4ts** [comment]
You can see #45

**Comment by bigmrw** [comment]
@yeln4ts Thank you and my apology for not searching the closed issues.  Thanks for your work on this project.
