### ISSUE TITLE
Export project as JSON using "this | toJSON"

### ISSUE THREAD

**Issue by T0my-commits** [pwndoc/pwndoc#539]
Hello everyone 👋

I'm trying to export my project to JSON in order to do some automation on the data it contains.
A few months ago I was just doing {this | toJSON} into a Word file to do it, but it not seems to work anymore.

Any idea to export my data projects from pwndoc?
Regards.

**Comment by yeln4ts** [comment]
`this` should not be used directly as it should not be accessible. It could have been fixed with the latest package updates.
I don't know if it would work but maybe using {. | toJSON} could work.

**Comment by yeln4ts** [comment]
I am currently working on a flexible backup feature which will allow to backup all or some part of your data. For now you can customize which part of your data you want to backup (vulns, custom data, audits, etc) but I also wanted to add a way to backup audits (single or multiple)
I just need to find the time to finish it but I think it will fit with your needs

**Comment by T0my-commits** [comment]
I think it too!
Thanks for your help and have a good day, I close the issue
