### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by ShojinSpear** [pwndoc/pwndoc#55]
Hi, 

First of all thanks for the great project.

I deploy pwndoc without no problems, but when i try to proxy the system  using nginx proxymanager project (NPM) I'm facing the problem "Something went wrong contacting backend". So when I try connect I'm redirect to https://domain:4242 from https://domain.

How can I manage this in NPM.

Thanks.

**Comment by yeln4ts** [comment]
I don't know if it's possible right now since the frontend is directly contacting the backend on its specific port. But if you manage to do it I'm interested. I was thinking of also doing this for the production environment but would have to change some config in the frontend.

**Comment by alexcoman** [comment]
Hello @ShojinSpear, @yeln4ts,

I've discovered this awesome project a few days ago, and I also would like to have it running behind a reverse proxy.
In my case, that reverse proxy is [traefik](https://traefik.io/).

An example of a Docker compose file for achieving that can be found at the following URL: [docker-compose.traefik.yml](https://github.com/alexcoman/pwndoc/blob/feature/reverse-proxy-support/docker-compose.traefik.yml )

The full patchset can be found [here](https://github.com/pwndoc/pwndoc/compare/master...alexcoman:feature/reverse-proxy-support).

@yeln4ts if you considered that the patch is useful I can prepare a merge request.

**Comment by yeln4ts** [comment]
I found a way to configure nginx for the production environment in order to proxy requests to the backend. So now when running in production you can just use the 8443 port where hostname:8443/api will be proxified to the backend
