### ISSUE TITLE
Unable to Built on Kali

### ISSUE THREAD

**Issue by x30r** [pwndoc/pwndoc#58]
Hi Team,

The error says the arch do not match. Am I supposed to use 64bit arch here?

The Error:
`$docker-compose up -d --build`
```
Pulling mongodb (mongo:)...
latest: Pulling from library/mongo
ERROR: no matching manifest for linux/386 in the manifest list entries
```

Arch of my system:
`$docker info  -f '{{.OSType}}/{{.Architecture}}'`
```
linux/i686
```

The arch of the image says null:
`$docker manifest inspect -v library/mongo | jq .[].Platform`
```
null
null
null
null
null
```
This means there is no arch defined for this docker image.
Should I now install Ubuntu VM and re-install it again?

**Comment by yeln4ts** [comment]
MongoDB no longer supports 32-bits x86 platforms (https://docs.mongodb.com/manual/installation/)
You should use a 64-bit architecture.
