### ISSUE TITLE
Vulnerabilities Not Available After Import

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [pwndoc/pwndoc#6]
Hi,

Thanks for this great tool. But, I'm having some issues. I wrote earlier about the template issues. I really hope I can figure that out. 

A new issue that I have is that after I import vulnerabilities, they are nowhere to be seen. The instructions are clear. I followed them precisely. Any idea what would prevent the findings from syncing?

**Comment by yeln4ts** [comment]
You import vulnerabilities from a previous export or from Serpico ? When you import the notification in the top right corner says what ? It should display either an error in red or the number of vulnerabilities imported in green or orange

**Comment by BetaMaxHeadroom** [comment]
I have tried this with both a yml file and a json file (from Serpico). I read a green message that said something similar to:

"86 vulnerabilities successfully imported."

But, no findings are listed when I open the vulnerabilities tab.

**Comment by yeln4ts** [comment]
Alright so it means they were correctly imported. Can you check in your debug network tab the status of the request to «/api/vulnerabilities» when accessing the Vulnerabilities page ?

**Comment by BetaMaxHeadroom** [comment]
This is embarrassing. But, I was up really late the past few days.

When I set the language initially, I wrote

Language "English"
Locale "USA"

I just look at the yml file again. I set both the language and Locale to "en". You can make fun of me. I deserve it for this.

I'll keep looking at how to update the template. I just break everything now.

**Comment by yeln4ts** [comment]
No worries it's not explicitely said in the Readme. But yes this is the locale parameter that is used to identify vulnerabilities and audits. For the language you can use "English" or whatever you want.
