### ISSUE TITLE
Template Generation Error Using Default Template

### ISSUE THREAD

**Issue by bennettwarner** [pwndoc/pwndoc#65]
Hi PwnDocs Team,

First off love the project; awesome work!
I am running into an issue with report generation. I am using the latest commit and the most recent template with no modifications. Attempting to generate / download a report I receive an undefined error. Poking around the docx a bit I removed 
` | changeID: 'VULN-'` 
from the vulnerabilities summer section. Making this modification and then attempting to generate a report give a new error: 
`The tag "image" is not inside a paragraph`

Any thoughts on why this is popping up? I tried changing all the image tags to conform to the `{-w:p images}{%image}` format and that netted me an undefined error.

Thanks so much!
Ben

**Comment by yeln4ts** [comment]
I think it could be an issue with the image module. Can you test with:
```
{#images}
{%image}
Image 1 - {caption}
{/images}
```
Each line is a paragraph

**Comment by bennettwarner** [comment]
I tried your recommended fix and am receiving an undefined error on generation.
Here is the the default template with your recommended modifications I tried.
[Default Template.docx](https://github.com/pwndoc/pwndoc/files/5816160/Default.Template.docx)

**Comment by yeln4ts** [comment]
The fix you did is ok but I found why the error. It's an issue with a check on the image module when there is no logo provided it returns an error. 
It should work if you remove the company.logo tags as is.
If else, I just pushed the fix if you want to update

**Comment by bennettwarner** [comment]
Awesome, thanks!

Just pulled the latest and its working. Looks like that was the issue.
