### ISSUE TITLE
How to retrieve custom category attributes?

### ISSUE THREAD

**Issue by z4t01** [pwndoc/pwndoc#66]
Hi,

I am trying your tool right now, very impressive :)

I have read the documentation but,for me, it is not too much clear how to "print", into my word template,  the values of my custom vuln category.

For example, I've created a custom category called "WEB" wich has the following "text" attributes:
* OWASP_ID
* custom_severity

Could you please provide me an example of the word syntax to insert these values into my word document?
Right now, I am obtaining an empty string.

Thanks and good job!

**Comment by yeln4ts** [comment]
Hi thank you,

I tried to make it the easiest way possible to use it. You can find this info in this section of the documentation: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=findings

There are 2 types of custom field: text (for HTML data) and input (for simple text input)
So in your case it would be accessible like this (ex: OWASP_ID as input and custom_severity as text):
```
Custom Severity:
{#custom_severity}
{@text | convertHTML}
                                            {#images}
                                            {%images}
                                    Image 1 - {caption}
                                            {/images}
{/custom_severity}

OWASP ID:
{owasp_id}
```

**Comment by tskzero** [comment]
Hi there,

Thanks for the great work.

I'm having issues with custom fields. Pretty much a cut and paste of what you've done to test that things work
The syntax makes sense but I keeping 
![image](https://user-images.githubusercontent.com/44367575/108437297-23272080-72a1-11eb-9ca9-f9f332b1acfc.png)

Document Template (cut and paste of the above)
![image](https://user-images.githubusercontent.com/44367575/108437384-4e117480-72a1-11eb-89cd-018802c81967.png)

Custom Fields section
![image](https://user-images.githubusercontent.com/44367575/108437424-6da89d00-72a1-11eb-8a5d-9062b039c993.png)

CHeers

**Comment by yeln4ts** [comment]
Is the {#custom_severity} inside a {#findings} ?
Is there any more information in the console log/network of the browser ?

**Comment by tskzero** [comment]
Hi yeln4ts,

The culprit is LibreOffice Writer. It's doing something to the file that is causing the templating engine to fail.

If I use word to save it all good, but if I save the template file in LibreOffice (Ctrl+S) and upload it fails. 

![image](https://user-images.githubusercontent.com/44367575/108583203-fa2f8a00-738b-11eb-8048-701db2c7b9ae.png)

**Comment by tskzero** [comment]
Also, nothing in log and it was embedded correctly. Afaict it's a libre writer issue.  So, the work around is to use word for the template.
