### ISSUE TITLE
Multiple remedations for one vuln

### ISSUE THREAD

**Issue by nervx** [pwndoc/pwndoc#70]
Hello,

Is it possible to have multiple remediations for one vuln with each remediation has his own identifier, it's for list them separately.

Example :

Vulnerability one has V1 identifier and has 2 remediations with identifier R1.1 and R1.2.

I use this identifier method because I resume vulns and remediations in 2 boards for my customers. In Serpico i did something like this :

![image](https://user-images.githubusercontent.com/13909748/105243652-9db03380-5b6f-11eb-838f-6174dbdf1cf5.png)

In blue it's my remediations.

**Comment by yeln4ts** [comment]
This is not possible since here remediations is an HTML field so it's not separated into an array of paragraph.
But you could just write one remediation for each paragraph or use the bullet or numbering system and simply display them in your table

**Comment by yeln4ts** [comment]
Question answered

**Comment by fbarre96** [comment]
The project would benefit from that feature. I would be interested in testing this tool if it added this.

**Comment by nervx** [comment]
@fbarre96 I dit it, I created some custom fields like it :
![image](https://user-images.githubusercontent.com/13909748/141263906-30c66b63-e996-499b-a8d5-9a658a5a0ac4.png)

You will find these fields here !
![image](https://user-images.githubusercontent.com/13909748/141264095-4b2c2410-771b-410e-bc0c-dee79d41450a.png)

In your docx you have to do something like that :
![image](https://user-images.githubusercontent.com/13909748/141264262-b0719703-24ac-4caa-8e7a-5c24eb0987d4.png)
