### ISSUE TITLE
Report Generation with Custom Sections

### ISSUE THREAD

**Issue by bigmrw** [pwndoc/pwndoc#72]
First, I want to say that I see a lot of value in this project, so thank you for creating and maintaining this.  I have been working through creating custom reporting templates and noticed that when using template variables (e.g. {company.name}) in the custom sections or any of the findings text boxes, they are never resolved when generating the template.  I am wondering if a basic reordering of how the report is programmatically generated could resolve this issue?  It is easy enough to do a find and replace in the generated report, but still wanted to point this out.

**Comment by yeln4ts** [comment]
Those variables can only be used in the template document, not directly in the application.
