### ISSUE TITLE
CVSS Vector

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc/pwndoc#73]
First thing first, thanks for the project, really good work.

I wanted to ask if currently CVSS vectors can be rendered in the following format (it's possible I've missed something):

CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H

As using:

CVSS:3.1/AV:{cvssObj.AV}/AC:{ cvssObj.AC}/PR:{cvssObj.PR}/UI:{cvssObj.UI}/S:{cvssObj.S}/C:{cvssObj.C}/I:{cvssObj.I}/A:{cvssObj.A}

Will create (as an example):

CVSS:3.1/AV:Network/AC:Low/PR:None/UI:None/S:Unchanged/C:High/I:High/A:High

**Comment by yeln4ts** [comment]
The string you want is stored in the field {cvssv3}. You can use it directly same way as {cvssScore} or {cvssSeverity}

**Comment by relaxedricky** [comment]
I thought I had tried that, clearly not. Thank you!

**Comment by xpelican** [comment]
Hi, I'm trying to make this same thing work in my DOCX template, but could not do it, could you please help?

I've tried to add to my DOCX template the following:

```
{#findings}
{cvssv3}
{cvss.cvssv3}
{findings.cvssv3}
{/findings}
```
They all come out as "undefined", so I guess I'm using the wrong syntax?
Any ideas what I'm doing wrong?

**Comment by relaxedricky** [comment]
Noted in the change log we have the [following](https://github.com/pwndoc/pwndoc/blob/master/CHANGELOG.md):

```
UPDATE ATTENTION
Changes to CVSS data require to update Word templates to avoid report generation errors
Replace {cvssv3} by {cvss.vectorString}
Replace {cvssScore} by {cvss.baseMetricScore}
Replace {cvssSeverity} by {cvss.baseSeverity}
Replace {@cvssColor} by {@cvss.cellColor}
```

**Comment by xpelican** [comment]
Thank you so much! Yeah, I was just throwing possibilities at the wall to see if anything sticks. :)

**Comment by relaxedricky** [comment]
nps
