### ISSUE TITLE
Plans for CVSS3.1?

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc/pwndoc#77]
Do you have plans to start using CVSS3.1?

I am open to trying to help with this the best I can if it is something you want to implement.

Any info to point me in the right direction is welcome.

**Comment by yeln4ts** [comment]
CVSS3.1 is mainly a clarification of used terms but calculs remain the same so there is no modification needed

**Comment by relaxedricky** [comment]
Yep you are correct, seems I was reading something earlier today that wasn't true and now I look a little silly :grimacing:
