### ISSUE TITLE
pwndoc-frontend - app/dist/spa: file does not exist

### ISSUE THREAD

**Issue by b4sh1t1** [pwndoc/pwndoc#78]
i'm getting this error in the build;

Step 11/13 : COPY --from=build /app/dist/spa /usr/share/nginx/html
ERROR: Service 'pwndoc-frontend' failed to build: COPY failed: stat app/dist/spa: file does not exist

this is my docker-compose - frontend template (default);

  pwndoc-frontend:
    build: ./frontend
    image: yeln4ts/pwndoc:frontend
    container_name: pwndoc-frontend
    restart: always
    ports:
      - 8443:8443
    networks:
      - backend

networks:
  backend:
      driver: bridge

any suggestion ?

**Comment by yeln4ts** [comment]
Did you have any error before ? 
Step 6 is the RUN npm run build, it's where the dist/spa is created

**Comment by yeln4ts** [comment]
Can you paste the full log of the docker-compose build/up for the frontend ?

**Comment by yeln4ts** [comment]
No response
