### ISSUE TITLE
CVSS "None" severity

### ISSUE THREAD

**Issue by AndyCyberSec** [pwndoc/pwndoc#83]
I just discovered this software and I am already in love! thanks for your work!
I was wondering if it's possible to have a CVSS base score of 0.0 "None", because I need to add also informational stuff. Selecting none on confidentiality, availability and integrity on PwnDoc cvss calculator the score is not calculated, while on the official cvss calculator, it is.

Does a workaround exist to manage also informational vulnerabilities?
Thank you

**Comment by yeln4ts** [comment]
it's not displayed but the finding data will be {cvssScore: '0.0', cvssSeverity: 'None'} so you can use it like you want in the docx template. 
For example, me in my report template if cvssSeverity is None then it's an informational finding.

**Comment by AndyCyberSec** [comment]
perfect, thank you!
