### ISSUE TITLE
Missing Executive Summary

### ISSUE THREAD

**Issue by AndyCyberSec** [pwndoc/pwndoc#86]
Hello, I am writing because reading the documentation I have noticed the presence of Executive Summary section in the left panel between "Findings" and  "Custom Sections" but I can't find it in my user interface. 

![Schermata 2021-01-29 alle 09 58 04](https://user-images.githubusercontent.com/20374411/106254088-9ac0dd00-6218-11eb-9239-f4697ec023cd.png)

**Comment by relaxedricky** [comment]
I have just updated pwndoc today and can confirm the above, looking at the gitpull, seems summary files have been deleted:

```
 frontend/src/pages/audits/edit/summary/index.vue        |  5 -----
 frontend/src/pages/audits/edit/summary/summary.html     | 17 -----------------
 frontend/src/pages/audits/edit/summary/summary.js       | 97 -------------------------------------------------------------------------------------------------
```

**Comment by yeln4ts** [comment]
Yes exactly executive summary can now be added through custom section. I didn't update the documentation yet

**Comment by yeln4ts** [comment]
Updated documentation
