### ISSUE TITLE
Question: Code Blocks

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc/pwndoc#88]
So the red box shows how pwndoc ends up showing my code block and the green box shows how it should be:

![Code Block](https://i.imgur.com/Lesg0Ijl.png)

I am guessing this is something to do with the new lines not being new lines.

I had a look [here](https://github.com/pwndoc/pwndoc/blob/8fb365fdd89138d59b4ef0afa2ceabd9f0b9b66f/backend/src/lib/html2ooxml.js) and line 123 looks like it is should handle multi-line code blocks, however, this doesn't seem to be working as I expect.

Could you offer any advice?

**Comment by yeln4ts** [comment]
This is because code blocks are not separated in paragraphs but use newlines. So when converting to open office xml format this is considered like soft returns so numbering won't work.
I can try to see if it's possible to use paragraphs instead of newlines.

**Comment by relaxedricky** [comment]
Closing as [fixed](https://github.com/pwndoc/pwndoc/commit/fd76a27be74b6f78090c20cbc4d55983c6999ef1)
