### ISSUE TITLE
Unable to edit data after update

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc/pwndoc#93]
I've just updated my install today and now I can't upload new templates, edit anything in custom datas, or import Vulnerabilities.

![No editing here](https://i.imgur.com/8LAVt1Y.png)

Could this be linked to the recent roles change?

I followed the normal update method:

`sudo -g docker docker-compose down

git pull

sudo -g docker docker-compose up -d --build`

My profile does say it is an admin.

**Comment by nobox910** [comment]
@relaxedricky let log out and log in again.

**Comment by relaxedricky** [comment]
I could have sworn I'd logged into a clean session, clearly not though.

Thank you. All sorted
