### ISSUE TITLE
Nmap import not working?

### ISSUE THREAD

**Issue by AndyCyberSec** [pwndoc/pwndoc#95]
Hello, I don't know if it's a bug or a problem of my installation but when I import nmap xml scan nothing happens. I only see the message "Successfully imported n hosts" but the page is still blank.

**Comment by yeln4ts** [comment]
You need to have defined at least one scope in the «General» section

**Comment by x1mdev** [comment]
Same issue here: After importing the nmap xml file the ip addresses are selectable in the "Associate imported hosts with Scopes" field. However, after saving and going to a different tab (i.e. General Information) the data seems to be gone when going back to the "Network Scan" tab.

**Comment by yeln4ts** [comment]
The nmap import is not saved on the server, it just allows you to associate hosts with Scopes. Only those associated hosts will be saved

**Comment by AndyCyberSec** [comment]
ok, great it's working!

So a quick recap:

1. Define the scope in general info
2. The scope will appear in network scan
3. Import nmap/nessus scan
4. Select all the hosts associated with the scope
5. Click the + symbol to effectively associate hosts with the scope
6. Save

I would add a mini tutorial to the documentation, the process wasn't clear to me.

Also as an enhancement would be cool to have the chance to add all the hosts at once, you know for huge networks.

Thanks!

**Comment by x1mdev** [comment]
I missed the last + symbol.. :') working now!

**Comment by noraj** [comment]
@AndyCyberSec There is documenttion [here](https://github.com/pwndoc/pwndoc/tree/master/docs) using [docsify](https://docsify.js.org) so it would be awesome if you have time to PR to document those steps. Thanks.

**Comment by AndyCyberSec** [comment]
> @AndyCyberSec There is documenttion [here](https://github.com/pwndoc/pwndoc/tree/master/docs) using [docsify](https://docsify.js.org) so it would be awesome if you have time to PR to document those steps. Thanks.

done!
