### ISSUE TITLE
Deleting a user can break pwndoc's audits page

### ISSUE THREAD

**Issue by mrnfrancesco** [pwndoc/pwndoc#96]
Deleting an user who created at least one audit will result in an error due to null creator reference.
This can break the audit page resulting in pwndoc to be unusable.

**Comment by yeln4ts** [comment]
This shouldn't happen since there is a check on creator existence. I just tested to remove a user and the result is just a blank space instead of username like it should be.
Do you have more information like the console log or screenshots ?

**Comment by mrnfrancesco** [comment]
The console have an error saying `e.creator is null`.
I have fixed the issue by directly editing the reference in the database.

**Comment by yeln4ts** [comment]
What commit version are you using ?

**Comment by mrnfrancesco** [comment]
It's not the latest one, maybe it is already fixed.
It is the edfec1e5d98b3163499d937d04d4d5a280c4ccfc

**Comment by yeln4ts** [comment]
Yes it's already fixed
